# Capstone 3: Sustainable Energy Recommendation System  
### "Leveraging Neural Collaborative Filtering for Sustainable Energy Insights"
Audrey Malloy 

Date Updated: April 15th, 2025

## Objectives for Data Wrangling
### 1. Handle Missing Data  
- Identify gaps in financial flows, renewable capacity, and energy share columns.  
- Implement imputation techniques where appropriate (mean, median, interpolation).  

### 2. Data Cleaning & Transformation  
- Convert categorical variables (e.g., "Entity" and "Density") into numerical formats.  
- Standardize units across energy and economic indicators.  
- Normalize numerical features to ensure comparability.  

### 3. Outlier Detection & Removal  
- Investigate extreme values in energy consumption and CO₂ emissions.  
- Apply statistical methods (z-score, IQR) to manage outliers effectively.  

### 4. Feature Engineering  
- Create new meaningful features (e.g., "Renewables-to-Fossil Ratio").  
- Construct interaction terms that capture dependencies between electricity sources.  

### 5. Geospatial Data Preparation  
- Ensure latitude and longitude are correctly formatted for graph-based relationships.  
- Use spatial clustering methods to group regions with similar energy dynamics.

### Data Overview:

- **Entity**: The name of the country or region for which the data is reported.
- **Year**: The year for which the data is reported, ranging from 2000 to 2020.
- **Access to electricity (% of population)**: The percentage of population with access to electricity.
- **Access to clean fuels for cooking (% of population)**: The percentage of the population with primary reliance on clean fuels.
- **Renewable-electricity-generating-capacity-per-capita**: Installed renewable energy capacity per person.
- **Financial flows to developing countries (US $)**: Aid and assistance from developed countries for clean energy projects.
  
- **Renewable energy share in total final energy consumption (%)**: Percentage of renewable energy in final energy consumption.
- **Electricity from fossil fuels (TWh)**: Electricity generated from fossil fuels (coal, oil, gas) in terawatt-hours.
- **Electricity from nuclear (TWh)**: Electricity generated from nuclear power in terawatt-hours.
- **Electricity from renewables (TWh)**: Electricity generated from renewable sources (hydro, solar, wind, etc.) in terawatt-hours.
- **Low-carbon electricity (% electricity)**: Percentage of electricity from low-carbon sources (nuclear and renewables).
- **Primary energy consumption per capita (kWh/person)**: Energy consumption per person in kilowatt-hours.
- **Energy intensity level of primary energy (MJ/$2011 PPP GDP)**: Energy use per unit of GDP at purchasing power parity.
- **Value_co2_emissions (metric tons per capita)**: Carbon dioxide emissions per person in metric tons.
- **Renewables (% equivalent primary energy)**: Equivalent primary energy that is derived from renewable sources.
- **GDP growth (annual %)**: Annual GDP growth rate based on constant local currency.
- **GDP per capita**: Gross domestic product per person.
- **Density (P/Km²)**: Population density in persons per square kilometer.
- **Land Area (Km²)**: Total land area in square kilometers.
- **Latitude**: Latitude of the country's centroid in decimal degrees.
- **Longitude**: Longitude of the country's centroid in decimal degrees.

In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.impute import SimpleImputer
import requests
import os

In [3]:
os.chdir('C:/Users/aamal/Desktop/Springboard/Springboard_DataScience/Capstone-3-Energy/data')
file_path = 'C:/Users/aamal/Desktop/Springboard/Springboard_DataScience/Capstone-3-Energy/data/global-data-on-sustainable-energy.csv'
df = pd.read_csv(file_path)

In [4]:
df.head()

,Entity,Year,Access to electricity (% of population),Access to clean fuels for cooking,Renewable-electricity-generating-capacity-per-capita,Financial flows to developing countries (US $),Renewable energy share in the total final energy consumption (%),Electricity from fossil fuels (TWh),Electricity from nuclear (TWh),Electricity from renewables (TWh),...,Primary energy consumption per capita (kWh/person),Energy intensity level of primary energy (MJ/$2017 PPP GDP),Value_co2_emissions_kt_by_country,Renewables (% equivalent primary energy),gdp_growth,gdp_per_capita,Density\n(P/Km2),Land Area(Km2),Latitude,Longitude
0,Afghanistan,2000,1.613591,6.2,9.22,20000.0,44.99,0.16,0.0,0.31,...,302.59482,1.64,760.000000,NaN,NaN,NaN,60,652230.0,33.93911,67.709953
1,Afghanistan,2001,4.074574,7.2,8.86,130000.0,45.60,0.09,0.0,0.50,...,236.89185,1.74,730.000000,NaN,NaN,NaN,60,652230.0,33.93911,67.709953
2,Afghanistan,2002,9.409158,8.2,8.47,3950000.0,37.83,0.13,0.0,0.56,...,210.86215,1.40,1029.999971,NaN,NaN,179.426579,60,652230.0,33.93911,67.709953
3,Afghanistan,2003,14.738506,9.5,8.09,25970000.0,36.66,0.31,0.0,0.63,...,229.96822,1.40,1220.000029,NaN,8.832278,190.683814,60,652230.0,33.93911,67.709953
4,Afghanistan,2004,20.064968,10.9,7.75,NaN,44.24,0.33,0.0,0.56,...,204.23125,1.20,1029.999971,NaN,1.414118,211.382074,60,652230.0,33.93911,67.709953

In [5]:
print(df.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3649 entries, 0 to 3648
Data columns (total 21 columns):
 #   Column                                                            Non-Null Count  Dtype
---  ------                                                            --------------  -----
 0   Entity                                                            3649 non-null   object
 1   Year                                                              3649 non-null   int64
 2   Access to electricity (% of population)                           3639 non-null   float64
 3   Access to clean fuels for cooking                                 3480 non-null   float64
 4   Renewable-electricity-generating-capacity-per-capita              2718 non-null   float64
 5   Financial flows to developing countries (US $)                    1560 non-null   float64
 6   Renewable energy share in the total final energy consumption (%)  3455 non-null   float64
 7   Electricity from fossil fuels (TWh)                               3628 non-null   float64
 8   Electricity from nuclear (TWh)                                    3523 non-null   float64
 9   Electricity from renewables (TWh)                                 3628 non-null   float64
 10  Low-carbon electricity (% electricity)                            3607 non-null   float64
 11  Primary energy consumption per capita (kWh/person)                3649 non-null   float64
 12  Energy intensity level of primary energy (MJ/$2017 PPP GDP)       3442 non-null   float64
 13  Value_co2_emissions_kt_by_country                                 3221 non-null   float64
 14  Renewables (% equivalent primary energy)                          1512 non-null   float64
 15  gdp_growth                                                        3332 non-null   float64
 16  gdp_per_capita                                                    3367 non-null   float64
 17  Density\n(P/Km2)                                                  3648 non-null   object
 18  Land Area(Km2)                                                    3648 non-null   float64
 19  Latitude                                                          3648 non-null   float64
 20  Longitude                                                         3648 non-null   float64
dtypes: float64(18), int64(1), object(2)
memory usage: 598.8+ KB
None

In [6]:
df.rename(columns={
    "Entity": "Entity",
    "Year": "Year",
    "Access to electricity (% of population)": "Electricity_Access",
    "Access to clean fuels for cooking": "Clean_Cooking_Fuels",
    "Renewable-electricity-generating-capacity-per-capita": "Renewable_Capacity",
    "Financial flows to developing countries (US $)": "Financial_Flows",
    "Renewable energy share in the total final energy consumption (%)": "Renewable_Share",
    "Electricity from fossil fuels (TWh)": "Fossil_Electricity",
    "Electricity from nuclear (TWh)": "Nuclear_Electricity",
    "Electricity from renewables (TWh)": "Renewable_Electricity",
    "Low-carbon electricity (% electricity)": "Low_Carbon_Electricity",
    "Primary energy consumption per capita (kWh/person)": "Energy_Consumption",
    "Energy intensity level of primary energy (MJ/$2017 PPP GDP)": "Energy_Intensity",
    "Value_co2_emissions_kt_by_country": "CO2_Emissions",
    "Renewables (% equivalent primary energy)": "Renewables_Percentage",
    "gdp_growth": "GDP_Growth",
    "gdp_per_capita": "GDP_Per_Capita",
    "Density\\n(P/Km2)": "Population_Density",
    "Land Area(Km2)": "Land_Area",
    "Latitude": "Latitude",
    "Longitude": "Longitude"
}, inplace=True)

### Handle missing and NA values:

In [7]:
print(df.isnull().sum())

Entity                       0
Year                         0
Electricity_Access          10
Clean_Cooking_Fuels        169
Renewable_Capacity         931
Financial_Flows           2089
Renewable_Share            194
Fossil_Electricity          21
Nuclear_Electricity        126
Renewable_Electricity       21
Low_Carbon_Electricity      42
Energy_Consumption           0
Energy_Intensity           207
CO2_Emissions              428
Renewables_Percentage     2137
GDP_Growth                 317
GDP_Per_Capita             282
Population_Density           1
Land_Area                    1
Latitude                     1
Longitude                    1
dtype: int64

EXPLANATIONS FOR MISSING VALUES^^^^^ Need to add

In [9]:
df["Electricity_Access"] = df["Electricity_Access"].fillna(df["Electricity_Access"].median())
df["Clean_Cooking_Fuels"] = df["Clean_Cooking_Fuels"].fillna(df["Clean_Cooking_Fuels"].median())
df["Fossil_Electricity"] = df["Fossil_Electricity"].fillna(df["Fossil_Electricity"].mean())

df["Renewable_Electricity"] = df["Renewable_Electricity"].fillna(df["Renewable_Electricity"].mean())

df["Low_Carbon_Electricity"] = df["Low_Carbon_Electricity"].fillna(df["Low_Carbon_Electricity"].mean())
df["Renewable_Share"]= df["Renewable_Share"].fillna(df["Renewable_Share"].median())

In [10]:
df.loc[:, "Financial_Flows"] = df["Financial_Flows"].fillna(0)
df.loc[:, "Renewables_Percentage"] = df["Renewables_Percentage"].fillna(0)

In [11]:
df["Renewable_Capacity"]= df["Renewable_Capacity"].fillna(0)

In [12]:
df["CO2_Emissions"] = df["CO2_Emissions"].interpolate(method="linear")
df["Energy_Intensity"] = df["Energy_Intensity"].interpolate(method="linear")

In [13]:
df.fillna( {
           "Population_Density": df["Population_Density"].ffill(), 
           "Land_Area": df["Land_Area"].ffill()}, inplace=True)

In [14]:
df.dropna(subset=["GDP_Per_Capita", "GDP_Growth", "Latitude", "Longitude"], inplace=True)

In [15]:
missing_nuclear_region = df.groupby("Entity")["Nuclear_Electricity"].apply(lambda x: x.isnull().sum())

print(missing_nuclear_region.sort_values(ascending=False))

Entity
Tuvalu          21
Kazakhstan      21
Malaysia        21
Saudi Arabia    21
Indonesia       21
                ..
Germany          0
Ghana            0
Greece           0
Grenada          0
Zimbabwe         0
Name: Nuclear_Electricity, Length: 164, dtype: int64

Countries that don't rely on Nuclear electricity fill NA values with 0:

In [16]:
df["Nuclear_Electricity"] = df["Nuclear_Electricity"].fillna(0).infer_objects(copy=False)

In [17]:
print(df.isnull().sum())

Entity                    0
Year                      0
Electricity_Access        0
Clean_Cooking_Fuels       0
Renewable_Capacity        0
Financial_Flows           0
Renewable_Share           0
Fossil_Electricity        0
Nuclear_Electricity       0
Renewable_Electricity     0
Low_Carbon_Electricity    0
Energy_Consumption        0
Energy_Intensity          0
CO2_Emissions             0
Renewables_Percentage     0
GDP_Growth                0
GDP_Per_Capita            0
Population_Density        0
Land_Area                 0
Latitude                  0
Longitude                 0
dtype: int64

In [18]:
df.describe()

,Year,Electricity_Access,Clean_Cooking_Fuels,Renewable_Capacity,Financial_Flows,Renewable_Share,Fossil_Electricity,Nuclear_Electricity,Renewable_Electricity,Low_Carbon_Electricity,Energy_Consumption,Energy_Intensity,CO2_Emissions,Renewables_Percentage,GDP_Growth,GDP_Per_Capita,Land_Area,Latitude,Longitude
count,3327.000000,3327.000000,3327.000000,3327.000000,3.327000e+03,3327.000000,3327.000000,3327.000000,3327.000000,3327.000000,3327.000000,3327.000000,3.327000e+03,3327.000000,3327.000000,3327.000000,3.327000e+03,3327.000000,3327.000000
mean,2010.083258,78.939515,63.923204,84.272549,4.220104e+07,33.020595,75.916419,13.977256,26.030736,38.235381,26316.343933,5.367094,1.619046e+05,5.342819,3.442334,13212.059684,6.626588e+05,18.261721,14.507692
std,6.036966,30.429090,38.270414,219.623685,2.054507e+08,29.290711,362.822004,75.061398,108.822168,34.074744,35716.445816,3.530948,7.703387e+05,11.756992,5.660445,19707.295067,1.646526e+06,24.659895,66.244741
min,2000.000000,1.252269,0.000000,0.000000,0.000000e+00,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.110000,1.000000e+01,0.000000,-62.075920,111.927225,2.100000e+01,-40.900557,-175.198242
25%,2005.000000,61.727257,26.100000,0.000000,0.000000e+00,7.855000,0.320000,0.000000,0.090000,5.711435,3094.157200,3.255000,2.290000e+03,0.000000,1.386902,1348.516340,2.805100e+04,1.836898,-10.940835
50%,2010.000000,98.361570,83.150000,8.870000,0.000000e+00,23.300000,3.510000,0.000000,1.790000,32.984450,13652.776000,4.390000,1.258500e+04,0.000000,3.558128,4576.387617,1.319570e+05,17.570692,19.145136
75%,2015.000000,100.000000,100.000000,71.750000,2.840000e+06,53.700000,29.870000,0.000000,10.995000,65.051720,33674.603500,6.105000,6.166500e+04,4.829156,5.811262,15432.023390,5.131200e+05,39.074208,45.079162
max,2020.000000,100.000000,100.000000,3060.190000,5.202310e+09,96.040000,5184.130000,809.410000,2184.940000,100.000010,262585.700000,32.570000,1.070722e+07,86.836586,123.139555,123514.196700,9.984670e+06,64.963051,178.065032

In [19]:
df.dtypes

Entity                     object
Year                        int64
Electricity_Access        float64
Clean_Cooking_Fuels       float64
Renewable_Capacity        float64
Financial_Flows           float64
Renewable_Share           float64
Fossil_Electricity        float64
Nuclear_Electricity       float64
Renewable_Electricity     float64
Low_Carbon_Electricity    float64
Energy_Consumption        float64
Energy_Intensity          float64
CO2_Emissions             float64
Renewables_Percentage     float64
GDP_Growth                float64
GDP_Per_Capita            float64
Population_Density         object
Land_Area                 float64
Latitude                  float64
Longitude                 float64
dtype: object

In [20]:
df["Population_Density"] = df["Population_Density"].str.replace(",", "").astype(float)

In [21]:
print(df[["Entity", "Year", "Population_Density"]].dtypes)  # Should show float for Population_Density
print(df["Population_Density"].isnull().sum())  # Should return 0

Entity                 object
Year                    int64
Population_Density    float64
dtype: object
0

In [22]:
df["Population_Density"] = pd.to_numeric(df["Population_Density"], errors="coerce")

In [23]:
print(df["Population_Density"].dtype)
print(df["Population_Density"].isnull().sum())

float64
0

In [24]:
entity_mapping = dict(zip(df["Entity"].astype("category").cat.categories, range(len(df["Entity"].astype("category").cat.categories))))
print(entity_mapping)

{'Afghanistan': 0, 'Albania': 1, 'Algeria': 2, 'Angola': 3, 'Antigua and Barbuda': 4, 'Argentina': 5, 'Armenia': 6, 'Aruba': 7, 'Australia': 8, 'Austria': 9, 'Azerbaijan': 10, 'Bahrain': 11, 'Bangladesh': 12, 'Barbados': 13, 'Belarus': 14, 'Belgium': 15, 'Belize': 16, 'Benin': 17, 'Bermuda': 18, 'Bhutan': 19, 'Bosnia and Herzegovina': 20, 'Botswana': 21, 'Brazil': 22, 'Bulgaria': 23, 'Burkina Faso': 24, 'Burundi': 25, 'Cambodia': 26, 'Cameroon': 27, 'Canada': 28, 'Cayman Islands': 29, 'Central African Republic': 30, 'Chad': 31, 'Chile': 32, 'China': 33, 'Colombia': 34, 'Comoros': 35, 'Costa Rica': 36, 'Croatia': 37, 'Cuba': 38, 'Cyprus': 39, 'Denmark': 40, 'Djibouti': 41, 'Dominica': 42, 'Dominican Republic': 43, 'Ecuador': 44, 'El Salvador': 45, 'Equatorial Guinea': 46, 'Eritrea': 47, 'Estonia': 48, 'Eswatini': 49, 'Ethiopia': 50, 'Fiji': 51, 'Finland': 52, 'France': 53, 'Gabon': 54, 'Georgia': 55, 'Germany': 56, 'Ghana': 57, 'Greece': 58, 'Grenada': 59, 'Guatemala': 60, 'Guinea': 61, 'Guinea-Bissau': 62, 'Guyana': 63, 'Haiti': 64, 'Honduras': 65, 'Hungary': 66, 'Iceland': 67, 'India': 68, 'Indonesia': 69, 'Iraq': 70, 'Ireland': 71, 'Israel': 72, 'Italy': 73, 'Jamaica': 74, 'Japan': 75, 'Jordan': 76, 'Kazakhstan': 77, 'Kenya': 78, 'Kiribati': 79, 'Kuwait': 80, 'Latvia': 81, 'Lebanon': 82, 'Lesotho': 83, 'Liberia': 84, 'Libya': 85, 'Lithuania': 86, 'Luxembourg': 87, 'Madagascar': 88, 'Malawi': 89, 'Malaysia': 90, 'Maldives': 91, 'Mali': 92, 'Malta': 93, 'Mauritania': 94, 'Mauritius': 95, 'Mexico': 96, 'Mongolia': 97, 'Montenegro': 98, 'Morocco': 99, 'Mozambique': 100, 'Myanmar': 101, 'Namibia': 102, 'Nauru': 103, 'Nepal': 104, 'Netherlands': 105, 'New Caledonia': 106, 'New Zealand': 107, 'Nicaragua': 108, 'Niger': 109, 'Nigeria': 110, 'North Macedonia': 111, 'Norway': 112, 'Oman': 113, 'Pakistan': 114, 'Panama': 115, 'Papua New Guinea': 116, 'Paraguay': 117, 'Peru': 118, 'Philippines': 119, 'Poland': 120, 'Portugal': 121, 'Puerto Rico': 122, 'Qatar': 123, 'Romania': 124, 'Rwanda': 125, 'Samoa': 126, 'Sao Tome and Principe': 127, 'Saudi Arabia': 128, 'Senegal': 129, 'Serbia': 130, 'Seychelles': 131, 'Sierra Leone': 132, 'Singapore': 133, 'Slovenia': 134, 'Solomon Islands': 135, 'Somalia': 136, 'South Africa': 137, 'South Sudan': 138, 'Spain': 139, 'Sri Lanka': 140, 'Sudan': 141, 'Suriname': 142, 'Sweden': 143, 'Switzerland': 144, 'Tajikistan': 145, 'Thailand': 146, 'Togo': 147, 'Tonga': 148, 'Trinidad and Tobago': 149, 'Tunisia': 150, 'Turkey': 151, 'Turkmenistan': 152, 'Tuvalu': 153, 'Uganda': 154, 'Ukraine': 155, 'United Arab Emirates': 156, 'United Kingdom': 157, 'United States': 158, 'Uruguay': 159, 'Uzbekistan': 160, 'Vanuatu': 161, 'Zambia': 162, 'Zimbabwe': 163}

In [25]:
#["Entity"] = df["Entity"].astype("category").cat.codes  # Convert country names to numeric codes
#df["Entity"].dtypes

### Handling Outilers

In [27]:
# Remove extreme outliers (e.g., beyond 3 standard deviations)
for col in ["GDP_Per_Capita", "CO2_Emissions", "Renewable_Share", "Energy_Intensity"]:
    df = df[np.abs(df[col] - df[col].mean()) <= (3 * df[col].std())]

### Normalize Numerical Features

In [29]:
from sklearn.preprocessing import MinMaxScaler

scaler = MinMaxScaler()
df[["GDP_Per_Capita", "Energy_Intensity", "CO2_Emissions", "Renewable_Share"]] = scaler.fit_transform(
    df[["GDP_Per_Capita", "Energy_Intensity", "CO2_Emissions", "Renewable_Share"]])

In [30]:
#Feature Engineering
df["Energy_Dependency"] = df["Renewable_Share"] * df["Financial_Flows"]
df["CO2_Intensity_Per_Capita"] = df["CO2_Emissions"] / df["Population_Density"]

In [31]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
df[["Energy_Dependency", "CO2_Intensity_Per_Capita"]] = scaler.fit_transform(df[["Energy_Dependency", "CO2_Intensity_Per_Capita"]])

In [32]:
print(df.columns)

Index(['Entity', 'Year', 'Electricity_Access', 'Clean_Cooking_Fuels',
       'Renewable_Capacity', 'Financial_Flows', 'Renewable_Share',
       'Fossil_Electricity', 'Nuclear_Electricity', 'Renewable_Electricity',
       'Low_Carbon_Electricity', 'Energy_Consumption', 'Energy_Intensity',
       'CO2_Emissions', 'Renewables_Percentage', 'GDP_Growth',
       'GDP_Per_Capita', 'Population_Density', 'Land_Area', 'Latitude',
       'Longitude', 'Energy_Dependency', 'CO2_Intensity_Per_Capita'],
      dtype='object')

In [33]:
df.info()
df.head()

<class 'pandas.core.frame.DataFrame'>
Index: 3142 entries, 3 to 3648
Data columns (total 23 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Entity                    3142 non-null   object
 1   Year                      3142 non-null   int64
 2   Electricity_Access        3142 non-null   float64
 3   Clean_Cooking_Fuels       3142 non-null   float64
 4   Renewable_Capacity        3142 non-null   float64
 5   Financial_Flows           3142 non-null   float64
 6   Renewable_Share           3142 non-null   float64
 7   Fossil_Electricity        3142 non-null   float64
 8   Nuclear_Electricity       3142 non-null   float64
 9   Renewable_Electricity     3142 non-null   float64
 10  Low_Carbon_Electricity    3142 non-null   float64
 11  Energy_Consumption        3142 non-null   float64
 12  Energy_Intensity          3142 non-null   float64
 13  CO2_Emissions             3142 non-null   float64
 14  Renewables_Percentage     3142 non-null   float64
 15  GDP_Growth                3142 non-null   float64
 16  GDP_Per_Capita            3142 non-null   float64
 17  Population_Density        3142 non-null   float64
 18  Land_Area                 3142 non-null   float64
 19  Latitude                  3142 non-null   float64
 20  Longitude                 3142 non-null   float64
 21  Energy_Dependency         3142 non-null   float64
 22  CO2_Intensity_Per_Capita  3142 non-null   float64
dtypes: float64(21), int64(1), object(1)
memory usage: 589.1+ KB

,Entity,Year,Electricity_Access,Clean_Cooking_Fuels,Renewable_Capacity,Financial_Flows,Renewable_Share,Fossil_Electricity,Nuclear_Electricity,Renewable_Electricity,...,CO2_Emissions,Renewables_Percentage,GDP_Growth,GDP_Per_Capita,Population_Density,Land_Area,Latitude,Longitude,Energy_Dependency,CO2_Intensity_Per_Capita
3,Afghanistan,2003,14.738506,9.50,8.09,25970000.0,0.381716,0.31,0.0,0.63,...,0.000493,0.0,8.832278,0.001068,60.0,652230.0,33.93911,67.709953,-0.071982,-0.201462
4,Afghanistan,2004,20.064968,10.90,7.75,0.0,0.460641,0.33,0.0,0.56,...,0.000415,0.0,1.414118,0.001354,60.0,652230.0,33.93911,67.709953,-0.144614,-0.201667
5,Afghanistan,2005,25.390894,12.20,7.51,9830000.0,0.352770,0.34,0.0,0.59,...,0.000627,0.0,11.229715,0.001779,60.0,652230.0,33.93911,67.709953,-0.119206,-0.201107
6,Afghanistan,2006,30.718690,13.85,7.40,10620000.0,0.332049,0.20,0.0,0.64,...,0.000712,0.0,5.357403,0.002079,60.0,652230.0,33.93911,67.709953,-0.118777,-0.200881
7,Afghanistan,2007,36.051010,15.30,7.25,15750000.0,0.299667,0.20,0.0,0.75,...,0.000717,0.0,13.826320,0.003408,60.0,652230.0,33.93911,67.709953,-0.110033,-0.200870

In [34]:
df.describe()

,Year,Electricity_Access,Clean_Cooking_Fuels,Renewable_Capacity,Financial_Flows,Renewable_Share,Fossil_Electricity,Nuclear_Electricity,Renewable_Electricity,Low_Carbon_Electricity,...,CO2_Emissions,Renewables_Percentage,GDP_Growth,GDP_Per_Capita,Population_Density,Land_Area,Latitude,Longitude,Energy_Dependency,CO2_Intensity_Per_Capita
count,3142.000000,3142.000000,3142.000000,3142.000000,3.142000e+03,3142.000000,3142.000000,3142.000000,3142.000000,3142.000000,...,3142.000000,3142.000000,3142.000000,3142.000000,3142.000000,3.142000e+03,3142.000000,3142.000000,3.142000e+03,3.142000e+03
mean,2010.078931,78.172628,62.794192,86.297791,4.308589e+07,0.352459,40.767936,8.829548,17.454812,38.348912,...,0.034573,5.081878,3.420967,0.152783,231.314768,5.649334e+05,17.409283,14.797663,-4.522869e-18,1.809148e-17
std,6.047104,30.573357,38.478899,223.977507,2.096183e+08,0.303265,115.562198,43.962331,54.425831,33.899363,...,0.085634,11.149937,5.695488,0.209929,730.175864,1.333619e+06,24.734190,66.327497,1.000159e+00,1.000159e+00
min,2000.000000,1.252269,0.000000,0.000000,0.000000e+00,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,-62.075920,0.000000,2.000000,2.100000e+01,-40.900557,-175.198242,-1.446136e-01,-2.027639e-01
25%,2005.000000,58.394294,24.000000,0.000000,0.000000e+00,0.092071,0.310000,0.000000,0.100000,5.882353,...,0.000916,0.000000,1.402864,0.016748,30.000000,2.874800e+04,1.373333,-9.696645,-1.446136e-01,-2.009069e-01
50%,2010.000000,97.700000,83.150000,11.005000,0.000000e+00,0.246668,3.465000,0.000000,1.775000,33.640520,...,0.004782,0.000000,3.602344,0.058493,84.000000,1.303700e+05,15.870032,19.374390,-1.446136e-01,-1.896010e-01
75%,2015.000000,100.000000,100.000000,73.395000,3.427500e+06,0.569398,29.317500,0.000000,10.107500,65.006385,...,0.024581,4.503730,5.776738,0.189192,206.000000,5.131200e+05,39.074208,45.038189,-1.390404e-01,-1.449973e-01
max,2020.000000,100.000000,100.000000,3060.190000,5.202310e+09,1.000000,2431.900000,789.880000,821.400000,100.000010,...,1.000000,86.836586,123.139555,1.000000,8358.000000,9.984670e+06,64.963051,178.065032,3.252648e+01,9.904354e+00

In [35]:
datapath = 'C:/Users/aamal/Desktop/Springboard/Springboard_DataScience/Capstone-3-Energy/data'
energy_data_cleaned = 'energy_data_cleaned.csv'
filepath= os.path.join(datapath, energy_data_cleaned)

df.to_csv(filepath, index= False)
print(f"Data saved successfully to '{filepath}'")

Data saved successfully to 'C:/Users/aamal/Desktop/Springboard/Springboard_DataScience/Capstone-3-Energy/data\energy_data_cleaned.csv'