# Capstone 3: Sustainable Energy Recommendation System  
### "Leveraging Neural Collaborative Filtering for Sustainable Energy Insights"
Audrey Malloy 

Date Updated: April 15th, 2025

## Objectives for Data Wrangling
### 1. Handle Missing Data  
- Identify gaps in financial flows, renewable capacity, and energy share columns.  
- Implement imputation techniques where appropriate (mean, median, interpolation).  

### 2. Data Cleaning & Transformation  
- Convert categorical variables (e.g., "Entity" and "Density") into numerical formats.  
- Standardize units across energy and economic indicators.  
- Normalize numerical features to ensure comparability.  

### 3. Outlier Detection & Removal  
- Investigate extreme values in energy consumption and CO₂ emissions.  
- Apply statistical methods (z-score, IQR) to manage outliers effectively.  

### 4. Feature Engineering  
- Create new meaningful features (e.g., "Renewables-to-Fossil Ratio").  
- Construct interaction terms that capture dependencies between electricity sources.  

### 5. Geospatial Data Preparation  
- Ensure latitude and longitude are correctly formatted for graph-based relationships.  
- Use spatial clustering methods to group regions with similar energy dynamics.

### Data Overview:

- **Entity**: The name of the country or region for which the data is reported.
- **Year**: The year for which the data is reported, ranging from 2000 to 2020.
- **Access to electricity (% of population)**: The percentage of population with access to electricity.
- **Access to clean fuels for cooking (% of population)**: The percentage of the population with primary reliance on clean fuels.
- **Renewable-electricity-generating-capacity-per-capita**: Installed renewable energy capacity per person.
- **Financial flows to developing countries (US $)**: Aid and assistance from developed countries for clean energy projects.
  
- **Renewable energy share in total final energy consumption (%)**: Percentage of renewable energy in final energy consumption.
- **Electricity from fossil fuels (TWh)**: Electricity generated from fossil fuels (coal, oil, gas) in terawatt-hours.
- **Electricity from nuclear (TWh)**: Electricity generated from nuclear power in terawatt-hours.
- **Electricity from renewables (TWh)**: Electricity generated from renewable sources (hydro, solar, wind, etc.) in terawatt-hours.
- **Low-carbon electricity (% electricity)**: Percentage of electricity from low-carbon sources (nuclear and renewables).
- **Primary energy consumption per capita (kWh/person)**: Energy consumption per person in kilowatt-hours.
- **Energy intensity level of primary energy (MJ/$2011 PPP GDP)**: Energy use per unit of GDP at purchasing power parity.
- **Value_co2_emissions (metric tons per capita)**: Carbon dioxide emissions per person in metric tons.
- **Renewables (% equivalent primary energy)**: Equivalent primary energy that is derived from renewable sources.
- **GDP growth (annual %)**: Annual GDP growth rate based on constant local currency.
- **GDP per capita**: Gross domestic product per person.
- **Density (P/Km²)**: Population density in persons per square kilometer.
- **Land Area (Km²)**: Total land area in square kilometers.
- **Latitude**: Latitude of the country's centroid in decimal degrees.
- **Longitude**: Longitude of the country's centroid in decimal degrees.

In [88]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.impute import SimpleImputer
import requests
import os

In [364]:
os.chdir('C:/Users/aamal/Desktop/Springboard/Springboard_DataScience/Capstone-3-Energy/data')
file_path = 'C:/Users/aamal/Desktop/Springboard/Springboard_DataScience/Capstone-3-Energy/data/global-data-on-sustainable-energy.csv'
df = pd.read_csv(file_path)

In [366]:
df.head()

,Entity,Year,Access to electricity (% of population),Access to clean fuels for cooking,Renewable-electricity-generating-capacity-per-capita,Financial flows to developing countries (US $),Renewable energy share in the total final energy consumption (%),Electricity from fossil fuels (TWh),Electricity from nuclear (TWh),Electricity from renewables (TWh),Low-carbon electricity (% electricity),Primary energy consumption per capita (kWh/person),Energy intensity level of primary energy (MJ/$2017 PPP GDP),Value_co2_emissions_kt_by_country,Renewables (% equivalent primary energy),gdp_growth,gdp_per_capita,Density\n(P/Km2),Land Area(Km2),Latitude,Longitude
0,Afghanistan,2000,1.613591,6.2,9.22,20000.0,44.99,0.16,0.0,0.31,65.957440,302.59482,1.64,760.000000,NaN,NaN,NaN,60,652230.0,33.93911,67.709953
1,Afghanistan,2001,4.074574,7.2,8.86,130000.0,45.60,0.09,0.0,0.50,84.745766,236.89185,1.74,730.000000,NaN,NaN,NaN,60,652230.0,33.93911,67.709953
2,Afghanistan,2002,9.409158,8.2,8.47,3950000.0,37.83,0.13,0.0,0.56,81.159424,210.86215,1.40,1029.999971,NaN,NaN,179.426579,60,652230.0,33.93911,67.709953
3,Afghanistan,2003,14.738506,9.5,8.09,25970000.0,36.66,0.31,0.0,0.63,67.021280,229.96822,1.40,1220.000029,NaN,8.832278,190.683814,60,652230.0,33.93911,67.709953
4,Afghanistan,2004,20.064968,10.9,7.75,NaN,44.24,0.33,0.0,0.56,62.921350,204.23125,1.20,1029.999971,NaN,1.414118,211.382074,60,652230.0,33.93911,67.709953

In [94]:
print(df.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3649 entries, 0 to 3648
Data columns (total 21 columns):
 #   Column                                                            Non-Null Count  Dtype
---  ------                                                            --------------  -----
 0   Entity                                                            3649 non-null   object
 1   Year                                                              3649 non-null   int64
 2   Access to electricity (% of population)                           3639 non-null   float64
 3   Access to clean fuels for cooking                                 3480 non-null   float64
 4   Renewable-electricity-generating-capacity-per-capita              2718 non-null   float64
 5   Financial flows to developing countries (US $)                    1560 non-null   float64
 6   Renewable energy share in the total final energy consumption (%)  3455 non-null   float64
 7   Electricity from fossil fuels (TWh)                               3628 non-null   float64
 8   Electricity from nuclear (TWh)                                    3523 non-null   float64
 9   Electricity from renewables (TWh)                                 3628 non-null   float64
 10  Low-carbon electricity (% electricity)                            3607 non-null   float64
 11  Primary energy consumption per capita (kWh/person)                3649 non-null   float64
 12  Energy intensity level of primary energy (MJ/$2017 PPP GDP)       3442 non-null   float64
 13  Value_co2_emissions_kt_by_country                                 3221 non-null   float64
 14  Renewables (% equivalent primary energy)                          1512 non-null   float64
 15  gdp_growth                                                        3332 non-null   float64
 16  gdp_per_capita                                                    3367 non-null   float64
 17  Density\n(P/Km2)                                                  3648 non-null   object
 18  Land Area(Km2)                                                    3648 non-null   float64
 19  Latitude                                                          3648 non-null   float64
 20  Longitude                                                         3648 non-null   float64
dtypes: float64(18), int64(1), object(2)
memory usage: 598.8+ KB
None

In [368]:
df.rename(columns={
    "Entity": "Entity",
    "Year": "Year",
    "Access to electricity (% of population)": "Electricity_Access",
    "Access to clean fuels for cooking": "Clean_Cooking_Fuels",
    "Renewable-electricity-generating-capacity-per-capita": "Renewable_Capacity",
    "Financial flows to developing countries (US $)": "Financial_Flows",
    "Renewable energy share in the total final energy consumption (%)": "Renewable_Share",
    "Electricity from fossil fuels (TWh)": "Fossil_Electricity",
    "Electricity from nuclear (TWh)": "Nuclear_Electricity",
    "Electricity from renewables (TWh)": "Renewable_Electricity",
    "Low-carbon electricity (% electricity)": "Low_Carbon_Electricity",
    "Primary energy consumption per capita (kWh/person)": "Energy_Consumption",
    "Energy intensity level of primary energy (MJ/$2017 PPP GDP)": "Energy_Intensity",
    "Value_co2_emissions_kt_by_country": "CO2_Emissions",
    "Renewables (% equivalent primary energy)": "Renewables_Percentage",
    "gdp_growth": "GDP_Growth",
    "gdp_per_capita": "GDP_Per_Capita",
    "Density\\n(P/Km2)": "Population_Density",
    "Land Area(Km2)": "Land_Area",
    "Latitude": "Latitude",
    "Longitude": "Longitude"
}, inplace=True)

### Handle missing and NA values:

In [370]:
print(df.isnull().sum())

Entity                       0
Year                         0
Electricity_Access          10
Clean_Cooking_Fuels        169
Renewable_Capacity         931
Financial_Flows           2089
Renewable_Share            194
Fossil_Electricity          21
Nuclear_Electricity        126
Renewable_Electricity       21
Low_Carbon_Electricity      42
Energy_Consumption           0
Energy_Intensity           207
CO2_Emissions              428
Renewables_Percentage     2137
GDP_Growth                 317
GDP_Per_Capita             282
Population_Density           1
Land_Area                    1
Latitude                     1
Longitude                    1
dtype: int64

# **1. Imputation Methods for Handling Missing Values**

Missing values can impact the performance and reliability of machine learning models. Different imputation techniques are used depending on the nature of the data and its distribution. Below are the methods applied in this project:

## **1.1 Median Imputation**
**Used for:**  
- `Electricity_Access`  
- `Clean_Cooking_Fuels`  
- `Renewable_Share`

**Why Median?**  
- The median is robust against **outliers**, making it preferable for variables that have **skewed distributions**.
- It ensures realistic estimates without being excessively influenced by extreme values.

In [372]:
df["Electricity_Access"] = df["Electricity_Access"].fillna(df["Electricity_Access"].median())
df["Clean_Cooking_Fuels"] = df["Clean_Cooking_Fuels"].fillna(df["Clean_Cooking_Fuels"].median())
df["Renewable_Share"] = df["Renewable_Share"].fillna(df["Renewable_Share"].median())

## **1.2 Mean Imputation**
**Used for:**  
- `Fossil_Electricity`  
- `Renewable_Electricity`  
- `Low_Carbon_Electiricty`
- `Energy_Intensity`

**Why Mean?**  
- The mean is effective when data is **normally distributed** or when missing values occur randomly.
- It maintains the general trend of the data while filing gaps.

In [374]:
df["Fossil_Electricity"] = df["Fossil_Electricity"].fillna(df["Fossil_Electricity"].mean())
df["Renewable_Electricity"] = df["Renewable_Electricity"].fillna(df["Renewable_Electricity"].mean())
df["Low_Carbon_Electricity"] = df["Low_Carbon_Electricity"].fillna(df["Low_Carbon_Electricity"].mean())

Filling Energy Intensity gaps using the country's historical averages

In [458]:
missing_intensity_rows = df[df[['Energy_Intensity']].isna().any(axis=1)][['Entity', 'Year', 'Energy_Intensity']]
print(missing_intensity_rows)

                                Entity  Year  Energy_Intensity
20                         Afghanistan  2020               NaN
41                             Albania  2020               NaN
62                             Algeria  2020               NaN
83                              Angola  2020               NaN
104                Antigua and Barbuda  2020               NaN
125                          Argentina  2020               NaN
146                            Armenia  2020               NaN
167                              Aruba  2020               NaN
188                          Australia  2020               NaN
209                            Austria  2020               NaN
230                         Azerbaijan  2020               NaN
251                            Bahamas  2020               NaN
272                            Bahrain  2020               NaN
293                         Bangladesh  2020               NaN
314                           Barbados  2020               NaN
335                            Belarus  2020               NaN
356                            Belgium  2020               NaN
377                             Belize  2020               NaN
398                              Benin  2020               NaN
419                            Bermuda  2020               NaN
440                             Bhutan  2020               NaN
461             Bosnia and Herzegovina  2020               NaN
482                           Botswana  2020               NaN
503                             Brazil  2020               NaN
524                           Bulgaria  2020               NaN
545                       Burkina Faso  2020               NaN
566                            Burundi  2020               NaN
587                           Cambodia  2020               NaN
608                           Cameroon  2020               NaN
629                             Canada  2020               NaN
650                     Cayman Islands  2020               NaN
671           Central African Republic  2020               NaN
692                               Chad  2020               NaN
713                              Chile  2020               NaN
734                              China  2020               NaN
755                           Colombia  2020               NaN
776                            Comoros  2020               NaN
797                              Congo  2020               NaN
818                         Costa Rica  2020               NaN
839                            Croatia  2020               NaN
860                               Cuba  2020               NaN
881                             Cyprus  2020               NaN
902                            Czechia  2020               NaN
923                            Denmark  2020               NaN
944                           Djibouti  2020               NaN
965                           Dominica  2020               NaN
986                 Dominican Republic  2020               NaN
1007                           Ecuador  2020               NaN
1028                             Egypt  2020               NaN
1049                       El Salvador  2020               NaN
1070                 Equatorial Guinea  2020               NaN
1112                           Estonia  2020               NaN
1133                          Eswatini  2020               NaN
1154                          Ethiopia  2020               NaN
1175                              Fiji  2020               NaN
1196                           Finland  2020               NaN
1217                            France  2020               NaN
1239                             Gabon  2020               NaN
1260                            Gambia  2020               NaN
1281                           Georgia  2020               NaN
1302                           Germany  2020               NaN
1323                             Ghana  2020               NaN
1344                            Greece  2020               NaN
1365                           Grenada  2020               NaN
1386                         Guatemala  2020               NaN
1407                            Guinea  2020               NaN
1428                     Guinea-Bissau  2020               NaN
1449                            Guyana  2020               NaN
1470                             Haiti  2020               NaN
1491                          Honduras  2020               NaN
1512                           Hungary  2020               NaN
1533                           Iceland  2020               NaN
1554                             India  2020               NaN
1575                         Indonesia  2020               NaN
1596                              Iraq  2020               NaN
1617                           Ireland  2020               NaN
1638                            Israel  2020               NaN
1659                             Italy  2020               NaN
1680                           Jamaica  2020               NaN
1701                             Japan  2020               NaN
1722                            Jordan  2020               NaN
1743                        Kazakhstan  2020               NaN
1764                             Kenya  2020               NaN
1785                          Kiribati  2020               NaN
1806                            Kuwait  2020               NaN
1848                            Latvia  2020               NaN
1869                           Lebanon  2020               NaN
1890                           Lesotho  2020               NaN
1911                           Liberia  2020               NaN
1932                             Libya  2020               NaN
1953                         Lithuania  2020               NaN
1974                        Luxembourg  2020               NaN
1995                        Madagascar  2020               NaN
2016                            Malawi  2020               NaN
2037                          Malaysia  2020               NaN
2058                          Maldives  2020               NaN
2079                              Mali  2020               NaN
2100                             Malta  2020               NaN
2121                        Mauritania  2020               NaN
2142                         Mauritius  2020               NaN
2163                            Mexico  2020               NaN
2184                          Mongolia  2020               NaN
2198                        Montenegro  2020               NaN
2219                           Morocco  2020               NaN
2240                        Mozambique  2020               NaN
2261                           Myanmar  2020               NaN
2282                           Namibia  2020               NaN
2303                             Nauru  2020               NaN
2324                             Nepal  2020               NaN
2345                       Netherlands  2020               NaN
2346                     New Caledonia  2000               NaN
2347                     New Caledonia  2001               NaN
2348                     New Caledonia  2002               NaN
2349                     New Caledonia  2003               NaN
2350                     New Caledonia  2004               NaN
2351                     New Caledonia  2005               NaN
2352                     New Caledonia  2006               NaN
2353                     New Caledonia  2007               NaN
2354                     New Caledonia  2008               NaN
2355                     New Caledonia  2009               NaN
2356                     New Caledonia  2010               NaN
2357                     New Caledonia  2011               NaN
2358                     New Caledonia  2012               NaN
2359                     New Caledonia  2013               NaN
2360                     New Caledonia  2014               NaN
2361                     New Caledonia  2015               NaN
2362                     New Caledonia  2016               NaN
2363                     New Caledonia  2017               NaN
2364                     New Caledonia  2018               NaN
2365                     New Caledonia  2019               NaN
2366                     New Caledonia  2020               NaN
2387                       New Zealand  2020               NaN
2408                         Nicaragua  2020               NaN
2429                             Niger  2020               NaN
2450                           Nigeria  2020               NaN
2471                   North Macedonia  2020               NaN
2492                            Norway  2020               NaN
2513                              Oman  2020               NaN
2534                          Pakistan  2020               NaN
2555                            Panama  2020               NaN
2576                  Papua New Guinea  2020               NaN
2597                          Paraguay  2020               NaN
2618                              Peru  2020               NaN
2639                       Philippines  2020               NaN
2660                            Poland  2020               NaN
2681                          Portugal  2020               NaN
2702                       Puerto Rico  2020               NaN
2723                             Qatar  2020               NaN
2744                           Romania  2020               NaN
2765                            Rwanda  2020               NaN
2786             Saint Kitts and Nevis  2020               NaN
2807                       Saint Lucia  2020               NaN
2828  Saint Vincent and the Grenadines  2020               NaN
2849                             Samoa  2020               NaN
2870             Sao Tome and Principe  2020               NaN
2891                      Saudi Arabia  2020               NaN
2912                           Senegal  2020               NaN
2926                            Serbia  2020               NaN
2947                        Seychelles  2020               NaN
2968                      Sierra Leone  2020               NaN
2989                         Singapore  2020               NaN
3031                          Slovenia  2020               NaN
3052                   Solomon Islands  2020               NaN
3073                           Somalia  2020               NaN
3094                      South Africa  2020               NaN
3098                       South Sudan  2016               NaN
3099                       South Sudan  2017               NaN
3100                       South Sudan  2018               NaN
3101                       South Sudan  2019               NaN
3102                       South Sudan  2020               NaN
3123                             Spain  2020               NaN
3144                         Sri Lanka  2020               NaN
3165                             Sudan  2020               NaN
3186                          Suriname  2020               NaN
3207                            Sweden  2020               NaN
3228                       Switzerland  2020               NaN
3249                        Tajikistan  2020               NaN
3270                          Thailand  2020               NaN
3291                              Togo  2020               NaN
3312                             Tonga  2020               NaN
3333               Trinidad and Tobago  2020               NaN
3354                           Tunisia  2020               NaN
3375                            Turkey  2020               NaN
3396                      Turkmenistan  2020               NaN
3417                            Tuvalu  2020               NaN
3438                            Uganda  2020               NaN
3459                           Ukraine  2020               NaN
3480              United Arab Emirates  2020               NaN
3501                    United Kingdom  2020               NaN
3522                     United States  2020               NaN
3543                           Uruguay  2020               NaN
3564                        Uzbekistan  2020               NaN
3585                           Vanuatu  2020               NaN
3602                             Yemen  2016               NaN
3603                             Yemen  2017               NaN
3604                             Yemen  2018               NaN
3605                             Yemen  2019               NaN
3606                             Yemen  2020               NaN
3627                            Zambia  2020               NaN

In [460]:
df['Energy_Intensity'] = df.groupby('Entity')['Energy_Intensity'].transform(lambda x: x.fillna(x.mean()))
#df['Energy_Intensity'] = df['Energy_Intensity'].interpolate(method='linear')

## **1.3 Zero Imputation**
**Used for:**  
- `Financial_Flows`  
- `Renewable Capacity`
- `Nuclear_Electricity`
- `Renewable_Percentage`

**Why Input Zero?**  
- When a missing value likely represents the **absence of data rather than an unknown value**, it can be replaced with 0. 
- May underestimate acutal values, so alternative approaches may be preferable.

In [376]:
df.loc[:, "Financial_Flows"] = df["Financial_Flows"].fillna(0)
df["Renewable_Capacity"]= df["Renewable_Capacity"].fillna(0)

In [378]:
missing_nuclear_region = df.groupby("Entity")["Nuclear_Electricity"].apply(lambda x: x.isnull().sum())

print(missing_nuclear_region.sort_values(ascending=False))

Entity
Tuvalu                              21
Kazakhstan                          21
Malaysia                            21
Saudi Arabia                        21
Chile                               21
Indonesia                           21
Pakistan                             0
New Zealand                          0
Nicaragua                            0
Niger                                0
Nigeria                              0
North Macedonia                      0
Norway                               0
Oman                                 0
Afghanistan                          0
Panama                               0
Netherlands                          0
Papua New Guinea                     0
Paraguay                             0
Peru                                 0
Philippines                          0
Poland                               0
Portugal                             0
Puerto Rico                          0
New Caledonia                        0
Nauru                                0
Nepal                                0
Romania                              0
Libya                                0
Lithuania                            0
Luxembourg                           0
Madagascar                           0
Malawi                               0
Maldives                             0
Mali                                 0
Malta                                0
Mauritania                           0
Mauritius                            0
Mexico                               0
Mongolia                             0
Montenegro                           0
Morocco                              0
Mozambique                           0
Myanmar                              0
Namibia                              0
Qatar                                0
Saint Kitts and Nevis                0
Rwanda                               0
Uganda                               0
Tajikistan                           0
Thailand                             0
Togo                                 0
Tonga                                0
Trinidad and Tobago                  0
Tunisia                              0
Turkey                               0
Turkmenistan                         0
Ukraine                              0
Lesotho                              0
United Arab Emirates                 0
United Kingdom                       0
United States                        0
Uruguay                              0
Uzbekistan                           0
Vanuatu                              0
Yemen                                0
Zambia                               0
Switzerland                          0
Sweden                               0
Suriname                             0
Sudan                                0
Saint Lucia                          0
Saint Vincent and the Grenadines     0
Samoa                                0
Sao Tome and Principe                0
Senegal                              0
Serbia                               0
Seychelles                           0
Sierra Leone                         0
Singapore                            0
Slovakia                             0
Slovenia                             0
Solomon Islands                      0
Somalia                              0
South Africa                         0
South Sudan                          0
Spain                                0
Sri Lanka                            0
Liberia                              0
Latvia                               0
Lebanon                              0
Chad                                 0
Bulgaria                             0
Burkina Faso                         0
Burundi                              0
Cambodia                             0
Cameroon                             0
Canada                               0
Cayman Islands                       0
Central African Republic             0
China                                0
Botswana                             0
Colombia                             0
Comoros                              0
Congo                                0
Costa Rica                           0
Croatia                              0
Cuba                                 0
Cyprus                               0
Czechia                              0
Brazil                               0
Bosnia and Herzegovina               0
Albania                              0
Azerbaijan                           0
Algeria                              0
Angola                               0
Antigua and Barbuda                  0
Argentina                            0
Armenia                              0
Aruba                                0
Australia                            0
Austria                              0
Bahamas                              0
Bhutan                               0
Bahrain                              0
Bangladesh                           0
Barbados                             0
Belarus                              0
Belgium                              0
Belize                               0
Benin                                0
Bermuda                              0
Denmark                              0
Djibouti                             0
Dominica                             0
Ireland                              0
Guinea-Bissau                        0
Guyana                               0
Haiti                                0
Honduras                             0
Hungary                              0
Iceland                              0
India                                0
Iraq                                 0
Israel                               0
Dominican Republic                   0
Italy                                0
Jamaica                              0
Japan                                0
Jordan                               0
Kenya                                0
Kiribati                             0
Kuwait                               0
Kyrgyzstan                           0
Guinea                               0
Guatemala                            0
Grenada                              0
Greece                               0
Ecuador                              0
Egypt                                0
El Salvador                          0
Equatorial Guinea                    0
Eritrea                              0
Estonia                              0
Eswatini                             0
Ethiopia                             0
Fiji                                 0
Finland                              0
France                               0
French Guiana                        0
Gabon                                0
Gambia                               0
Georgia                              0
Germany                              0
Ghana                                0
Zimbabwe                             0
Name: Nuclear_Electricity, dtype: int64

Countries that don't rely on **nuclear electricity** fill NA values with 0.

In [380]:
df["Nuclear_Electricity"] = df["Nuclear_Electricity"].fillna(0).infer_objects(copy=False)

#### **Applying a Conservative Approach: Filling with 0%**

For countries that consistently lack renewable energy adoption data, a **conservative imputation strategy** is to assume `0%` for **Renewables_Percentage**. This assumption is justified under the following conditions:
- **No reported investments in renewable energy** from external sources such as the World Bank or IEA.
- **High reliance on fossil fuels** with little evidence of renewable energy deployment.
- **Consistent missing data across all years**, indicating a lack of official tracking or policy support for renewables.

If a country has **no recorded use of renewable energy** and no policy incentives for adoption, this method ensures accurate classification of non-renewable energy economies.

##### **References**
- [International Energy Agency (IEA) – Renewable Energy Report](https://www.iea.org/reports)
- [World Bank – Sustainable Energy Data](https://data.worldbank.org)

In [382]:
missing_countries = df[df["Renewables_Percentage"].isna()]["Entity"].unique()

# Display the list
print(missing_countries)

['Afghanistan' 'Albania' 'Angola' 'Antigua and Barbuda' 'Armenia' 'Aruba'
 'Bahamas' 'Bahrain' 'Barbados' 'Belize' 'Benin' 'Bermuda' 'Bhutan'
 'Bosnia and Herzegovina' 'Botswana' 'Burkina Faso' 'Burundi' 'Cambodia'
 'Cameroon' 'Cayman Islands' 'Central African Republic' 'Chad' 'Comoros'
 'Congo' 'Costa Rica' 'Cuba' 'Djibouti' 'Dominica' 'Dominican Republic'
 'El Salvador' 'Equatorial Guinea' 'Eritrea' 'Eswatini' 'Ethiopia' 'Fiji'
 'French Guiana' 'Gabon' 'Gambia' 'Georgia' 'Ghana' 'Grenada' 'Guatemala'
 'Guinea' 'Guinea-Bissau' 'Guyana' 'Haiti' 'Honduras' 'Jamaica' 'Jordan'
 'Kenya' 'Kiribati' 'Kyrgyzstan' 'Lebanon' 'Lesotho' 'Liberia' 'Libya'
 'Madagascar' 'Malawi' 'Maldives' 'Mali' 'Malta' 'Mauritania' 'Mauritius'
 'Mongolia' 'Montenegro' 'Mozambique' 'Myanmar' 'Namibia' 'Nauru' 'Nepal'
 'New Caledonia' 'Nicaragua' 'Niger' 'Nigeria' 'Panama' 'Papua New Guinea'
 'Paraguay' 'Puerto Rico' 'Rwanda' 'Saint Kitts and Nevis' 'Saint Lucia'
 'Saint Vincent and the Grenadines' 'Samoa' 'Sao Tome and Principe'
 'Senegal' 'Serbia' 'Seychelles' 'Sierra Leone' 'Solomon Islands'
 'Somalia' 'South Sudan' 'Sudan' 'Suriname' 'Tajikistan' 'Togo' 'Tonga'
 'Tunisia' 'Tuvalu' 'Uganda' 'Uruguay' 'Vanuatu' 'Yemen' 'Zambia'
 'Zimbabwe']

In [384]:
df.loc[df["Renewables_Percentage"].isna(), "Renewables_Percentage"] = 0

## **1.4 Forward Filling for Population Density**
**Used for:**  
- `Population_Density`
- `Land_Area`

**Why Forward Fill?**  
- Population density **changes gradually** rather than fluctuating significantly from year to year.  
- Filling missing values with the last known value ensures **continuity** in the data while maintaining historical trends.  
- Avoids unrealistic jumps that could occur with other imputation methods like mean or median substitution.

In [386]:
df.fillna( {
           "Population_Density": df["Population_Density"].ffill(), 
           "Land_Area": df["Land_Area"].ffill()}, inplace=True)

## **1.5. Manually Impute Correct Data**
**Used for:**  
- `Latitude`
- `Longitude`

In [388]:
df[["Latitude", "Longitude"]].isna().sum()

Latitude     1
Longitude    1
dtype: int64

In [390]:
df[df[["Latitude", "Longitude"]].isna().any(axis=1)]

,Entity,Year,Electricity_Access,Clean_Cooking_Fuels,Renewable_Capacity,Financial_Flows,Renewable_Share,Fossil_Electricity,Nuclear_Electricity,Renewable_Electricity,Low_Carbon_Electricity,Energy_Consumption,Energy_Intensity,CO2_Emissions,Renewables_Percentage,GDP_Growth,GDP_Per_Capita,Population_Density,Land_Area,Latitude,Longitude
1218,French Guiana,2000,98.36157,83.15,702.29,0.0,23.84,0.43,0.0,0.0,0.0,13692.394,NaN,NaN,0.0,NaN,NaN,119,643801.0,NaN,NaN

In [392]:
df.loc[df["Entity"] == "French Guiana", ["Latitude", "Longitude"]] = [4.003, -53.002]

## **1.6 Mixed Approach for GDP Imputation Process**
**Features:**  
- `GDP_Growth`
- `GDP_Per_Capita`

1️⃣ Adding Missing GDP Data
- Merged external GDP data from World Bank Data for countries:
Bahamas, Cayman Islands, Czechia, Djibouti, Eritrea, Gambia, Nauru, New Caledonia, Somalia, South Sudan, St. Kitts and Nevis, St. Lucia, St. Vincent and Grenadines, Yemen.

2️⃣ Filling GDP Growth from GDP Per Capita
- For Djibouti, New Caledonia, Sao Tome and Principe, Yemen, computed GDP Growth using year-over-year percentage change in GDP per capita.

3️⃣ Data Cleaning
- Removed countries with no GDP data: Kyrgyzstan, Slovakia, French Guiana.

4️⃣ Applying Mean Imputation
- Used country-level averages to fill missing GDP Growth and GDP Per Capita.

In [394]:
print(df[["GDP_Growth", "GDP_Per_Capita"]].isna().sum())

df[df["GDP_Per_Capita"].isna()]["Entity"].unique()

GDP_Growth        317
GDP_Per_Capita    282
dtype: int64

array(['Afghanistan', 'Aruba', 'Bahamas', 'Cayman Islands', 'Congo',
       'Czechia', 'Egypt', 'Eritrea', 'French Guiana', 'Gambia',
       'Kyrgyzstan', 'Nauru', 'New Caledonia', 'Saint Kitts and Nevis',
       'Saint Lucia', 'Saint Vincent and the Grenadines',
       'Sao Tome and Principe', 'Slovakia', 'Somalia', 'South Sudan',
       'Turkmenistan', 'Yemen'], dtype=object)

In [422]:
GDP_data = pd.read_csv('GDP_cleaned.csv')

                               Entity  Year    GDP_Growth GDP_Per_Capita
0                             Bahamas  2000   4.148419308    24940.07751
1                             Bahamas  2001   2.626009827    25371.92377
2                             Bahamas  2002   2.704956247    26781.61959
3                             Bahamas  2003  -1.264916676    26429.12478
4                             Bahamas  2004   0.882373745    26650.29342
5                             Bahamas  2005   3.396084205    28602.41819
6                             Bahamas  2006   2.516592217    29184.78651
7                             Bahamas  2007   1.446099912    30051.84896
8                             Bahamas  2008   -2.32364807    29392.38244
9                             Bahamas  2009  -4.175428056     27512.9131
10                            Bahamas  2010   1.538662487    27473.10043
11                            Bahamas  2011   0.613170736    27090.83768
12                            Bahamas  2012   2.997903207    28552.02427
13                            Bahamas  2013  -2.863309257    27432.95343
14                            Bahamas  2014   1.847260843    28705.61708
15                            Bahamas  2015   0.996758611    30289.40225
16                            Bahamas  2016  -0.961908777    30266.58592
17                            Bahamas  2017   2.799518639    31337.18325
18                            Bahamas  2018    2.62988986    32124.40511
19                            Bahamas  2019  -1.357265209    32979.54013
20                            Bahamas  2020  -21.42346307    25155.67254
21                     Cayman Islands  2000            ..             ..
22                     Cayman Islands  2001            ..             ..
23                     Cayman Islands  2002            ..             ..
24                     Cayman Islands  2003            ..             ..
25                     Cayman Islands  2004            ..             ..
26                     Cayman Islands  2005            ..             ..
27                     Cayman Islands  2006            ..    87085.09374
28                     Cayman Islands  2007   3.162625227    89888.26182
29                     Cayman Islands  2008  -0.357401201    89655.11962
30                     Cayman Islands  2009  -7.200482447    81373.57115
31                     Cayman Islands  2010  -2.715635262    76837.66996
32                     Cayman Islands  2011   1.169062198    75280.96076
33                     Cayman Islands  2012   1.229753657    75101.59136
34                     Cayman Islands  2013    1.27933102    75113.73324
35                     Cayman Islands  2014   2.654527985    75845.30604
36                     Cayman Islands  2015   2.833122226    76379.20951
37                     Cayman Islands  2016   3.239974339    77802.25416
38                     Cayman Islands  2017   3.184045923    80053.94445
39                     Cayman Islands  2018   4.267267452    83865.55316
40                     Cayman Islands  2019   3.915635342    88254.29037
41                     Cayman Islands  2020  -4.954806408    82338.79829
42                            Czechia  2000   4.010669619    6062.921528
43                            Czechia  2001   2.917219546    6669.074948
44                            Czechia  2002   1.513459483    8101.260186
45                            Czechia  2003   3.300836831    9852.456779
46                            Czechia  2004   4.736339704    11782.55467
47                            Czechia  2005   6.375028858    13442.49163
48                            Czechia  2006   6.623172985    15259.07882
49                            Czechia  2007   5.488825961    18452.65328
50                            Czechia  2008   2.612268052    22774.70451
51                            Czechia  2009  -4.798324168    19817.42158
52                            Czechia  2010   2.714665115    20160.43551
53                            Czechia  2011   1.772380837    22049.10808
54                            Czechia  2012  -0.770668176     20014.0354
55                            Czechia  2013  -0.041812408     20260.4955
56                            Czechia  2014   2.245212186    20038.41632
57                            Czechia  2015    4.95875849    17931.59877
58                            Czechia  2016   2.580870147    18753.96867
59                            Czechia  2017   5.173565288    20913.19763
60                            Czechia  2018   2.830305894    23705.93298
61                            Czechia  2019   3.565776572      24062.719
62                            Czechia  2020  -5.304879546    23472.89155
63                           Djibouti  2000            ..    737.6121836
64                           Djibouti  2001            ..    742.1337911
65                           Djibouti  2002            ..    743.0132704
66                           Djibouti  2003            ..    764.6344652
67                           Djibouti  2004            ..    806.2616529
68                           Djibouti  2005            ..    844.4483574
69                           Djibouti  2006            ..    898.4646281
70                           Djibouti  2007            ..    969.5732202
71                           Djibouti  2008            ..    1119.152333
72                           Djibouti  2009            ..    1150.937586
73                           Djibouti  2010            ..    1213.233526
74                           Djibouti  2011            ..    1306.345528
75                           Djibouti  2012            ..    1400.193579
76                           Djibouti  2013            ..    2074.296689
77                           Djibouti  2014   7.061543242    2208.678103
78                           Djibouti  2015   7.526108919    2376.125547
79                           Djibouti  2016   7.123432337    2510.430008
80                           Djibouti  2017   5.458091517    2618.955211
81                           Djibouti  2018   4.774416888    2718.085323
82                           Djibouti  2019     5.5451306    2837.171033
83                           Djibouti  2020   1.316363242    2881.999245
84                            Eritrea  2000  -3.141985903    314.3573968
85                            Eritrea  2001   8.755435528    325.4091615
86                            Eritrea  2002   3.005429192    304.7757565
87                            Eritrea  2003  -2.655515925    348.9503271
88                            Eritrea  2004   1.451735566    426.8409479
89                            Eritrea  2005   2.574449551    412.7530792
90                            Eritrea  2006  -0.969217111    447.9974047
91                            Eritrea  2007   1.426822211    480.4476237
92                            Eritrea  2008  -9.783030018     490.066956
93                            Eritrea  2009   3.876501528    642.9257229
94                            Eritrea  2010   2.194190349    539.6995121
95                            Eritrea  2011   8.679800101    688.6816596
96                            Eritrea  2012            ..             ..
97                            Eritrea  2013            ..             ..
98                            Eritrea  2014            ..             ..
99                            Eritrea  2015            ..             ..
100                           Eritrea  2016            ..             ..
101                           Eritrea  2017            ..             ..
102                           Eritrea  2018            ..             ..
103                           Eritrea  2019            ..             ..
104                           Eritrea  2020            ..             ..
105                            Gambia  2000   5.500000216    538.0540723
106                            Gambia  2001   5.800000243    459.8030684
107                            Gambia  2002   -3.25000015     376.531027
108                            Gambia  2003   6.869999622    308.7191234
109                            Gambia  2004   7.050000001    593.2853463
110                            Gambia  2005  -2.351729362    616.4836579
111                            Gambia  2006  -0.555580977    614.5443079
112                            Gambia  2007   3.043249508    724.7264072
113                            Gambia  2008   6.255905534    859.1276714
114                            Gambia  2009   6.665724308    774.8880309
115                            Gambia  2010    5.90833581    801.0333727
116                            Gambia  2011  -8.130444223    710.6084115
117                            Gambia  2012   5.241569246    692.5793616
118                            Gambia  2013    2.87276879    653.8627133
119                            Gambia  2014  -1.407382495    568.0045356
120                            Gambia  2015   4.058073804    619.5363643
121                            Gambia  2016   1.943359655    650.0565013
122                            Gambia  2017   4.822611249    642.5226413
123                            Gambia  2018   7.234890333     696.219807
124                            Gambia  2019    6.22205316     738.186752
125                            Gambia  2020   0.591487288    720.3351434
126                             Nauru  2000  -6.856193232    2648.601529
127                             Nauru  2001  -6.761117247     2232.30874
128                             Nauru  2002   -9.97126891    2084.648245
129                             Nauru  2003   0.284637232    2463.282591
130                             Nauru  2004  -4.314906396    3040.513499
131                             Nauru  2005  -0.355648874    2992.403828
132                             Nauru  2006   8.328760806    2910.141458
133                             Nauru  2007  -22.18530498    2272.152913
134                             Nauru  2008   20.38090759    3756.845312
135                             Nauru  2009    -5.6519328    4410.567647
136                             Nauru  2010  -0.159976911    4735.920005
137                             Nauru  2011   14.39463342    6480.904513
138                             Nauru  2012    25.2793205    9817.368722
139                             Nauru  2013   3.647740417    8974.518869
140                             Nauru  2014   16.42333564    9193.097844
141                             Nauru  2015   2.698017274    7703.431499
142                             Nauru  2016   4.363240539    8724.307003
143                             Nauru  2017  -6.011229987    9613.412091
144                             Nauru  2018  -1.219122015    11408.69476
145                             Nauru  2019   8.486736592    10776.82846
146                             Nauru  2020   1.981819494    10695.69933
147                     New Caledonia  2000   2.100108827    15329.72972
148                     New Caledonia  2001            ..    14482.36063
149                     New Caledonia  2002            ..    16104.55204
150                     New Caledonia  2003            ..    20768.10615
151                     New Caledonia  2004            ..    24475.64885
152                     New Caledonia  2005            ..    25528.29184
153                     New Caledonia  2006            ..    28193.25376
154                     New Caledonia  2007            ..    35177.65353
155                     New Caledonia  2008            ..    35723.90332
156                     New Caledonia  2009            ..    33836.49408
157                     New Caledonia  2010            ..    35798.90848
158                     New Caledonia  2011            ..    38835.94019
159                     New Caledonia  2012            ..     35559.5672
160                     New Caledonia  2013            ..    36671.15668
161                     New Caledonia  2014            ..    37816.95586
162                     New Caledonia  2015            ..    30858.72371
163                     New Caledonia  2016            ..    30782.85444
164                     New Caledonia  2017            ..    32354.71028
165                     New Caledonia  2018   3.995707282    34902.89688
166                     New Caledonia  2019  -1.400000002    33411.33588
167                     New Caledonia  2020  -2.400000001     33270.3306
168                           Somalia  2000   7.110314311    386.1192744
169                           Somalia  2001   7.110314311    244.9148425
170                           Somalia  2002   7.630267293    229.5989183
171                           Somalia  2003   7.630267293    286.2730252
172                           Somalia  2004   7.110314311    375.4103262
173                           Somalia  2005   7.110314311    439.9799078
174                           Somalia  2006   6.486370733    457.9966622
175                           Somalia  2007   6.694351926    479.6356281
176                           Somalia  2008   6.694351926    507.0374433
177                           Somalia  2009   6.694351926    246.5132517
178                           Somalia  2010   6.694351926    219.2024539
179                           Somalia  2011   6.694351926    235.3259456
180                           Somalia  2012   6.694351926    350.2619467
181                           Somalia  2013   10.95929145     393.398705
182                           Somalia  2014   8.978005906     429.431656
183                           Somalia  2015   10.46218841    445.5830786
184                           Somalia  2016   7.034872974     460.928492
185                           Somalia  2017   14.73579515     510.939953
186                           Somalia  2018   2.054314856    509.5258024
187                           Somalia  2019   2.824313365    539.8939316
188                           Somalia  2020  -2.752481039    518.1847785
189                       South Sudan  2000            ..             ..
190                       South Sudan  2001            ..             ..
191                       South Sudan  2002            ..             ..
192                       South Sudan  2003            ..             ..
193                       South Sudan  2004            ..             ..
194                       South Sudan  2005            ..             ..
195                       South Sudan  2006            ..             ..
196                       South Sudan  2007            ..             ..
197                       South Sudan  2008            ..    1654.211535
198                       South Sudan  2009    5.04164188    1323.220687
199                       South Sudan  2010   5.493416395     1498.27035
200                       South Sudan  2011  -4.640316736     1448.98435
201                       South Sudan  2012  -46.08212237    1109.260501
202                       South Sudan  2013   13.12973114    1650.189434
203                       South Sudan  2014   3.373648477    1242.734502
204                       South Sudan  2015  -10.79336463    1080.147186
205                       South Sudan  2016            ..             ..
206                       South Sudan  2017            ..             ..
207                       South Sudan  2018            ..             ..
208                       South Sudan  2019            ..             ..
209                       South Sudan  2020            ..             ..
210             Saint Kitts and Nevis  2000   10.04280842    9319.655451
211             Saint Kitts and Nevis  2001    5.25344983    10022.59192
212             Saint Kitts and Nevis  2002   1.367715073    10453.65871
213             Saint Kitts and Nevis  2003   -3.93339486    10175.62954
214             Saint Kitts and Nevis  2004   3.996346661    10944.61837
215             Saint Kitts and Nevis  2005   9.732820703    11783.78672
216             Saint Kitts and Nevis  2006     3.1503812    13837.84953
217             Saint Kitts and Nevis  2007   0.600602327    14757.95798
218             Saint Kitts and Nevis  2008   11.31703583    16604.94486
219             Saint Kitts and Nevis  2009  -3.404740154    16503.41193
220             Saint Kitts and Nevis  2010  -0.054194207    16622.94579
221             Saint Kitts and Nevis  2011   1.616607304    17832.45729
222             Saint Kitts and Nevis  2012  -0.737636737     17532.0559
223             Saint Kitts and Nevis  2013   5.727280872    18580.13019
224             Saint Kitts and Nevis  2014   7.576966023    20219.39542
225             Saint Kitts and Nevis  2015   0.694135528    20328.80035
226             Saint Kitts and Nevis  2016   3.932703193    21387.54155
227             Saint Kitts and Nevis  2017   0.220941147    22464.98996
228             Saint Kitts and Nevis  2018   2.003525498    22901.38164
229             Saint Kitts and Nevis  2019   2.831267379    23595.49232
230             Saint Kitts and Nevis  2020  -15.35445176    18859.01904
231                       Saint Lucia  2000   0.048748554    5879.561914
232                       Saint Lucia  2001  -3.408063962    5570.452471
233                       Saint Lucia  2002   0.416450493    5567.894284
234                       Saint Lucia  2003   4.264611487    6058.606221
235                       Saint Lucia  2004    7.26740887    6494.600349
236                       Saint Lucia  2005  -0.410304726    6863.436419
237                       Saint Lucia  2006   6.195257291    7611.178567
238                       Saint Lucia  2007   1.691618574    7964.382115
239                       Saint Lucia  2008    4.94932194    8516.960755
240                       Saint Lucia  2009  -2.828899548    8250.521807
241                       Saint Lucia  2010   0.330018546    8673.687203
242                       Saint Lucia  2011   4.326942805     9128.99442
243                       Saint Lucia  2012  -0.108756148    9260.300066
244                       Saint Lucia  2013  -2.005024374    9576.234634
245                       Saint Lucia  2014   1.520874352    10044.82184
246                       Saint Lucia  2015   0.100928143    10334.92256
247                       Saint Lucia  2016   3.428096951     10638.1902
248                       Saint Lucia  2017   3.381374723    11333.19639
249                       Saint Lucia  2018   2.886197652    11642.74032
250                       Saint Lucia  2019  -0.700859002    11794.20565
251                       Saint Lucia  2020  -24.36115535    8411.199418
252  Saint Vincent and the Grenadines  2000   1.639031904    3768.955366
253  Saint Vincent and the Grenadines  2001    1.74823102    4071.086011
254  Saint Vincent and the Grenadines  2002   5.342127074    4303.279768
255  Saint Vincent and the Grenadines  2003   6.691336654    4499.614542
256  Saint Vincent and the Grenadines  2004   4.114698804    4873.489477
257  Saint Vincent and the Grenadines  2005   2.488557339    5157.393739
258  Saint Vincent and the Grenadines  2006   6.996926268    5744.827862
259  Saint Vincent and the Grenadines  2007   3.322968598    6398.191235
260  Saint Vincent and the Grenadines  2008   0.404640809    6598.905315
261  Saint Vincent and the Grenadines  2009  -1.378193606    6463.787773
262  Saint Vincent and the Grenadines  2010  -4.470467935     6551.96836
263  Saint Vincent and the Grenadines  2011  -0.606276651    6527.689969
264  Saint Vincent and the Grenadines  2012   1.169112184    6713.807686
265  Saint Vincent and the Grenadines  2013   2.462484172    7072.467372
266  Saint Vincent and the Grenadines  2014   1.250254369    7168.828753
267  Saint Vincent and the Grenadines  2015   2.783161194    7353.735561
268  Saint Vincent and the Grenadines  2016   4.145931682    7656.900429
269  Saint Vincent and the Grenadines  2017   1.448830634     7988.04445
270  Saint Vincent and the Grenadines  2018   3.175611442    8428.126772
271  Saint Vincent and the Grenadines  2019   0.661727444    8743.332021

In [424]:
df['GDP_Growth'] = pd.to_numeric(df['GDP_Growth'], errors='coerce')
df['GDP_Per_Capita'] = pd.to_numeric(df['GDP_Per_Capita'], errors='coerce')

GDP_data['GDP_Growth'] = pd.to_numeric(GDP_data['GDP_Growth'], errors='coerce')
GDP_data['GDP_Per_Capita'] = pd.to_numeric(GDP_data['GDP_Per_Capita'], errors='coerce')


df.set_index(['Entity', 'Year'], inplace=True)
GDP_data.set_index(['Entity', 'Year'], inplace=True)


df.update(GDP_data)


df.reset_index(inplace=True)

print(df.head())

        Entity  Year  Electricity_Access  Clean_Cooking_Fuels  \
0  Afghanistan  2000            1.613591                  6.2
1  Afghanistan  2001            4.074574                  7.2
2  Afghanistan  2002            9.409158                  8.2
3  Afghanistan  2003           14.738506                  9.5
4  Afghanistan  2004           20.064968                 10.9

   Renewable_Capacity  Financial_Flows  Renewable_Share  Fossil_Electricity  \
0                9.22          20000.0            44.99                0.16
1                8.86         130000.0            45.60                0.09
2                8.47        3950000.0            37.83                0.13
3                8.09       25970000.0            36.66                0.31
4                7.75              0.0            44.24                0.33

   Nuclear_Electricity  Renewable_Electricity  Low_Carbon_Electricity  \
0                  0.0                   0.31               65.957440
1                  0.0                   0.50               84.745766
2                  0.0                   0.56               81.159424
3                  0.0                   0.63               67.021280
4                  0.0                   0.56               62.921350

   Energy_Consumption  Energy_Intensity  CO2_Emissions  Renewables_Percentage  \
0           302.59482              1.64     760.000000                    0.0
1           236.89185              1.74     730.000000                    0.0
2           210.86215              1.40    1029.999971                    0.0
3           229.96822              1.40    1220.000029                    0.0
4           204.23125              1.20    1029.999971                    0.0

   GDP_Growth  GDP_Per_Capita Population_Density  Land_Area  Latitude  \
0         NaN             NaN                 60   652230.0  33.93911
1         NaN             NaN                 60   652230.0  33.93911
2         NaN      179.426579                 60   652230.0  33.93911
3    8.832278      190.683814                 60   652230.0  33.93911
4    1.414118      211.382074                 60   652230.0  33.93911

   Longitude
0  67.709953
1  67.709953
2  67.709953
3  67.709953
4  67.709953

In [426]:
missing_gdp_rows = df[df[['GDP_Growth', 'GDP_Per_Capita']].isna().any(axis=1)][['Entity', 'Year', 'GDP_Growth', 'GDP_Per_Capita']]
print(missing_gdp_rows)

                     Entity  Year  GDP_Growth  GDP_Per_Capita
0               Afghanistan  2000         NaN             NaN
1               Afghanistan  2001         NaN             NaN
2               Afghanistan  2002         NaN      179.426579
165                   Aruba  2018         NaN    30253.279360
166                   Aruba  2019         NaN             NaN
167                   Aruba  2020         NaN             NaN
630          Cayman Islands  2000         NaN             NaN
631          Cayman Islands  2001         NaN             NaN
632          Cayman Islands  2002         NaN             NaN
633          Cayman Islands  2003         NaN             NaN
634          Cayman Islands  2004         NaN             NaN
635          Cayman Islands  2005         NaN             NaN
636          Cayman Islands  2006         NaN    87085.093740
924                Djibouti  2000         NaN      737.612184
925                Djibouti  2001         NaN      742.133791
926                Djibouti  2002         NaN      743.013270
927                Djibouti  2003         NaN      764.634465
928                Djibouti  2004         NaN      806.261653
929                Djibouti  2005         NaN      844.448357
930                Djibouti  2006         NaN      898.464628
931                Djibouti  2007         NaN      969.573220
932                Djibouti  2008         NaN     1119.152333
933                Djibouti  2009         NaN     1150.937586
934                Djibouti  2010         NaN     1213.233526
935                Djibouti  2011         NaN     1306.345528
936                Djibouti  2012         NaN     1400.193579
937                Djibouti  2013         NaN     2074.296689
1083                Eritrea  2012         NaN             NaN
1084                Eritrea  2013         NaN             NaN
1085                Eritrea  2014         NaN             NaN
1086                Eritrea  2015         NaN             NaN
1087                Eritrea  2016         NaN             NaN
1088                Eritrea  2017         NaN             NaN
1089                Eritrea  2018         NaN             NaN
1090                Eritrea  2019         NaN             NaN
1091                Eritrea  2020         NaN             NaN
1218          French Guiana  2000         NaN             NaN
1807             Kyrgyzstan  2000         NaN             NaN
1808             Kyrgyzstan  2001         NaN             NaN
1809             Kyrgyzstan  2002         NaN             NaN
1810             Kyrgyzstan  2003         NaN             NaN
1811             Kyrgyzstan  2004         NaN             NaN
1812             Kyrgyzstan  2005         NaN             NaN
1813             Kyrgyzstan  2006         NaN             NaN
1814             Kyrgyzstan  2007         NaN             NaN
1815             Kyrgyzstan  2008         NaN             NaN
1816             Kyrgyzstan  2009         NaN             NaN
1817             Kyrgyzstan  2010         NaN             NaN
1818             Kyrgyzstan  2011         NaN             NaN
1819             Kyrgyzstan  2012         NaN             NaN
1820             Kyrgyzstan  2013         NaN             NaN
1821             Kyrgyzstan  2014         NaN             NaN
1822             Kyrgyzstan  2015         NaN             NaN
1823             Kyrgyzstan  2016         NaN             NaN
1824             Kyrgyzstan  2017         NaN             NaN
1825             Kyrgyzstan  2018         NaN             NaN
1826             Kyrgyzstan  2019         NaN             NaN
1827             Kyrgyzstan  2020         NaN             NaN
1891                Liberia  2000         NaN      306.833864
2347          New Caledonia  2001         NaN    14482.360630
2348          New Caledonia  2002         NaN    16104.552040
2349          New Caledonia  2003         NaN    20768.106150
2350          New Caledonia  2004         NaN    24475.648850
2351          New Caledonia  2005         NaN    25528.291840
2352          New Caledonia  2006         NaN    28193.253760
2353          New Caledonia  2007         NaN    35177.653530
2354          New Caledonia  2008         NaN    35723.903320
2355          New Caledonia  2009         NaN    33836.494080
2356          New Caledonia  2010         NaN    35798.908480
2357          New Caledonia  2011         NaN    38835.940190
2358          New Caledonia  2012         NaN    35559.567200
2359          New Caledonia  2013         NaN    36671.156680
2360          New Caledonia  2014         NaN    37816.955860
2361          New Caledonia  2015         NaN    30858.723710
2362          New Caledonia  2016         NaN    30782.854440
2363          New Caledonia  2017         NaN    32354.710280
2703                  Qatar  2000         NaN    29976.167630
2850  Sao Tome and Principe  2000         NaN             NaN
2851  Sao Tome and Principe  2001         NaN      524.669872
2990               Slovakia  2000         NaN             NaN
2991               Slovakia  2001         NaN             NaN
2992               Slovakia  2002         NaN             NaN
2993               Slovakia  2003         NaN             NaN
2994               Slovakia  2004         NaN             NaN
2995               Slovakia  2005         NaN             NaN
2996               Slovakia  2006         NaN             NaN
2997               Slovakia  2007         NaN             NaN
2998               Slovakia  2008         NaN             NaN
2999               Slovakia  2009         NaN             NaN
3000               Slovakia  2010         NaN             NaN
3001               Slovakia  2011         NaN             NaN
3002               Slovakia  2012         NaN             NaN
3003               Slovakia  2013         NaN             NaN
3004               Slovakia  2014         NaN             NaN
3005               Slovakia  2015         NaN             NaN
3006               Slovakia  2016         NaN             NaN
3007               Slovakia  2017         NaN             NaN
3008               Slovakia  2018         NaN             NaN
3009               Slovakia  2019         NaN             NaN
3010               Slovakia  2020         NaN             NaN
3098            South Sudan  2016         NaN             NaN
3099            South Sudan  2017         NaN             NaN
3100            South Sudan  2018         NaN             NaN
3101            South Sudan  2019         NaN             NaN
3102            South Sudan  2020         NaN             NaN
3396           Turkmenistan  2020         NaN             NaN
3605                  Yemen  2019         NaN      623.376165
3606                  Yemen  2020         NaN      559.564673

In [428]:
# List of countries where GDP growth needs to be filled
countries_to_fill = ['Djibouti', 'New Caledonia', 'Sao Tome and Principe', 'Yemen']

# Loop through each country and compute GDP growth from GDP per capita
for country in countries_to_fill:
    df.loc[df['Entity'] == country, 'GDP_Growth'] = df.loc[df['Entity'] == country, 'GDP_Per_Capita'].pct_change() * 100

print(df[df['Entity'].isin(countries_to_fill)][['Entity', 'Year', 'GDP_Growth', 'GDP_Per_Capita']])

                     Entity  Year  GDP_Growth  GDP_Per_Capita
924                Djibouti  2000         NaN      737.612184
925                Djibouti  2001    0.613006      742.133791
926                Djibouti  2002    0.118507      743.013270
927                Djibouti  2003    2.909934      764.634465
928                Djibouti  2004    5.444064      806.261653
929                Djibouti  2005    4.736267      844.448357
930                Djibouti  2006    6.396634      898.464628
931                Djibouti  2007    7.914456      969.573220
932                Djibouti  2008   15.427315     1119.152333
933                Djibouti  2009    2.840119     1150.937586
934                Djibouti  2010    5.412625     1213.233526
935                Djibouti  2011    7.674697     1306.345528
936                Djibouti  2012    7.184014     1400.193579
937                Djibouti  2013   48.143565     2074.296689
938                Djibouti  2014    6.478409     2208.678103
939                Djibouti  2015    7.581342     2376.125547
940                Djibouti  2016    5.652246     2510.430008
941                Djibouti  2017    4.322973     2618.955211
942                Djibouti  2018    3.785101     2718.085323
943                Djibouti  2019    4.381235     2837.171033
944                Djibouti  2020    1.580032     2881.999245
2346          New Caledonia  2000         NaN    15329.729720
2347          New Caledonia  2001   -5.527619    14482.360630
2348          New Caledonia  2002   11.201153    16104.552040
2349          New Caledonia  2003   28.957987    20768.106150
2350          New Caledonia  2004   17.852098    24475.648850
2351          New Caledonia  2005    4.300777    25528.291840
2352          New Caledonia  2006   10.439249    28193.253760
2353          New Caledonia  2007   24.773302    35177.653530
2354          New Caledonia  2008    1.552832    35723.903320
2355          New Caledonia  2009   -5.283323    33836.494080
2356          New Caledonia  2010    5.799698    35798.908480
2357          New Caledonia  2011    8.483587    38835.940190
2358          New Caledonia  2012   -8.436446    35559.567200
2359          New Caledonia  2013    3.125993    36671.156680
2360          New Caledonia  2014    3.124524    37816.955860
2361          New Caledonia  2015  -18.399768    30858.723710
2362          New Caledonia  2016   -0.245860    30782.854440
2363          New Caledonia  2017    5.106271    32354.710280
2364          New Caledonia  2018    7.875782    34902.896880
2365          New Caledonia  2019   -4.273459    33411.335880
2366          New Caledonia  2020   -0.422028    33270.330600
2850  Sao Tome and Principe  2000         NaN             NaN
2851  Sao Tome and Principe  2001         NaN      524.669872
2852  Sao Tome and Principe  2002   10.093686      577.628404
2853  Sao Tome and Principe  2003   17.504257      678.737964
2854  Sao Tome and Principe  2004    9.809726      745.320300
2855  Sao Tome and Principe  2005   16.259412      866.504996
2856  Sao Tome and Principe  2006    1.914824      883.097041
2857  Sao Tome and Principe  2007    1.559370      896.867791
2858  Sao Tome and Principe  2008   22.510277     1098.755219
2859  Sao Tome and Principe  2009   -2.807465     1067.908053
2860  Sao Tome and Principe  2010    2.093131     1090.260763
2861  Sao Tome and Principe  2011   15.068031     1254.541598
2862  Sao Tome and Principe  2012    6.064248     1330.620114
2863  Sao Tome and Principe  2013   17.596941     1564.768548
2864  Sao Tome and Principe  2014   13.145659     1770.467688
2865  Sao Tome and Principe  2015  -10.488304     1584.775657
2866  Sao Tome and Principe  2016    7.276887     1700.097997
2867  Sao Tome and Principe  2017    6.688405     1813.807434
2868  Sao Tome and Principe  2018    7.702351     1953.513257
2869  Sao Tome and Principe  2019    1.743855     1987.579702
2870  Sao Tome and Principe  2020    8.566235     2157.840446
3586                  Yemen  2000         NaN      493.235183
3587                  Yemen  2001   -1.235501      487.141258
3588                  Yemen  2002    5.357836      513.241487
3589                  Yemen  2003    6.948853      548.905883
3590                  Yemen  2004   14.342375      627.632023
3591                  Yemen  2005   16.972984      734.159909
3592                  Yemen  2006   10.291112      809.713128
3593                  Yemen  2007    9.953234      890.305768
3594                  Yemen  2008   20.367167     1071.635833
3595                  Yemen  2009   -9.554769      969.243510
3596                  Yemen  2010   19.186050     1155.203053
3597                  Yemen  2011    2.707052     1186.475006
3598                  Yemen  2012    4.936950     1245.050683
3599                  Yemen  2013   10.738466     1378.750030
3600                  Yemen  2014    3.729043     1430.164210
3601                  Yemen  2015   -4.754029     1362.173794
3602                  Yemen  2016  -28.396845      975.359407
3603                  Yemen  2017  -16.834148      811.165964
3604                  Yemen  2018  -21.854807      633.887206
3605                  Yemen  2019   -1.658188      623.376165
3606                  Yemen  2020  -10.236434      559.564673

In [466]:
df = df[~df['Entity'].isin(['Kyrgyzstan', 'Slovakia', 'French Guiana', 'Eritrea', 'New Caledonia'])]

In [440]:
missing_gdp = df[df[['GDP_Growth', 'GDP_Per_Capita']].isna().any(axis=1)][['Entity', 'Year', 'GDP_Growth', 'GDP_Per_Capita']]
print(missing_gdp)

                     Entity  Year  GDP_Growth  GDP_Per_Capita
0               Afghanistan  2000         NaN             NaN
1               Afghanistan  2001         NaN             NaN
2               Afghanistan  2002         NaN      179.426579
165                   Aruba  2018         NaN    30253.279360
166                   Aruba  2019         NaN             NaN
167                   Aruba  2020         NaN             NaN
630          Cayman Islands  2000         NaN             NaN
631          Cayman Islands  2001         NaN             NaN
632          Cayman Islands  2002         NaN             NaN
633          Cayman Islands  2003         NaN             NaN
634          Cayman Islands  2004         NaN             NaN
635          Cayman Islands  2005         NaN             NaN
636          Cayman Islands  2006         NaN    87085.093740
924                Djibouti  2000         NaN      737.612184
1891                Liberia  2000         NaN      306.833864
2346          New Caledonia  2000         NaN    15329.729720
2703                  Qatar  2000         NaN    29976.167630
2850  Sao Tome and Principe  2000         NaN             NaN
2851  Sao Tome and Principe  2001         NaN      524.669872
3098            South Sudan  2016         NaN             NaN
3099            South Sudan  2017         NaN             NaN
3100            South Sudan  2018         NaN             NaN
3101            South Sudan  2019         NaN             NaN
3102            South Sudan  2020         NaN             NaN
3396           Turkmenistan  2020         NaN             NaN
3586                  Yemen  2000         NaN      493.235183

In [446]:
df['GDP_Growth'] = df.groupby('Entity')['GDP_Growth'].transform(lambda x: x.fillna(x.mean()))
df['GDP_Per_Capita'] = df.groupby('Entity')['GDP_Per_Capita'].transform(lambda x: x.fillna(x.mean()))

In [470]:
print(df.isna().sum())

Entity                      0
Year                        0
Electricity_Access          0
Clean_Cooking_Fuels         0
Renewable_Capacity          0
Financial_Flows             0
Renewable_Share             0
Fossil_Electricity          0
Nuclear_Electricity         0
Renewable_Electricity       0
Low_Carbon_Electricity      0
Energy_Consumption          0
Energy_Intensity            0
CO2_Emissions             380
Renewables_Percentage       0
GDP_Growth                  0
GDP_Per_Capita              0
Population_Density          0
Land_Area                   0
Latitude                    0
Longitude                   0
dtype: int64

In [468]:
# Filter rows where Energy_Intensity or CO2_Emissions is missing
missing_rows = df[df[['Energy_Intensity', 'CO2_Emissions']].isna().any(axis=1)]

# Display the relevant columns for analysis
print(missing_rows[['Entity', 'Year', 'Energy_Intensity', 'CO2_Emissions']])

                                Entity  Year  Energy_Intensity  CO2_Emissions
20                         Afghanistan  2020          2.039000            NaN
41                             Albania  2020          3.177500            NaN
62                             Algeria  2020          4.498500            NaN
83                              Angola  2020          2.896500            NaN
104                Antigua and Barbuda  2020          3.624000            NaN
125                          Argentina  2020          3.497500            NaN
146                            Armenia  2020          4.396500            NaN
164                              Aruba  2017          3.130000            NaN
165                              Aruba  2018          3.070000            NaN
166                              Aruba  2019          3.200000            NaN
167                              Aruba  2020         10.577000            NaN
188                          Australia  2020          5.230500            NaN
209                            Austria  2020          3.166000            NaN
230                         Azerbaijan  2020          6.834500            NaN
231                            Bahamas  2000          2.330000            NaN
232                            Bahamas  2001          2.190000            NaN
233                            Bahamas  2002          2.230000            NaN
234                            Bahamas  2003          2.320000            NaN
235                            Bahamas  2004          2.270000            NaN
236                            Bahamas  2005          2.100000            NaN
237                            Bahamas  2006          2.000000            NaN
238                            Bahamas  2007          2.000000            NaN
239                            Bahamas  2008          2.080000            NaN
240                            Bahamas  2009          2.230000            NaN
241                            Bahamas  2010          2.140000            NaN
242                            Bahamas  2011          2.350000            NaN
243                            Bahamas  2012          2.500000            NaN
244                            Bahamas  2013          2.980000            NaN
245                            Bahamas  2014          2.650000            NaN
246                            Bahamas  2015          2.330000            NaN
247                            Bahamas  2016          2.120000            NaN
248                            Bahamas  2017          2.180000            NaN
249                            Bahamas  2018          2.720000            NaN
250                            Bahamas  2019          2.530000            NaN
251                            Bahamas  2020          2.312500            NaN
272                            Bahrain  2020          9.582500            NaN
293                         Bangladesh  2020          2.865000            NaN
314                           Barbados  2020          4.074000            NaN
335                            Belarus  2020          8.336000            NaN
356                            Belgium  2020          4.587500            NaN
377                             Belize  2020          5.678000            NaN
398                              Benin  2020          5.606000            NaN
416                            Bermuda  2017          1.770000            NaN
417                            Bermuda  2018          1.970000            NaN
418                            Bermuda  2019          1.650000            NaN
419                            Bermuda  2020          1.552500            NaN
440                             Bhutan  2020         11.476500            NaN
461             Bosnia and Herzegovina  2020          6.315000            NaN
482                           Botswana  2020          3.300000            NaN
503                             Brazil  2020          3.896500            NaN
524                           Bulgaria  2020          6.541000            NaN
545                       Burkina Faso  2020          5.058000            NaN
566                            Burundi  2020          8.500500            NaN
587                           Cambodia  2020          5.400000            NaN
608                           Cameroon  2020          5.074500            NaN
629                             Canada  2020          7.725500            NaN
647                     Cayman Islands  2017          1.870000            NaN
648                     Cayman Islands  2018          1.900000            NaN
649                     Cayman Islands  2019          2.060000            NaN
650                     Cayman Islands  2020          1.939000            NaN
671           Central African Republic  2020          7.903500            NaN
692                               Chad  2020          4.675500            NaN
713                              Chile  2020          3.781500            NaN
734                              China  2020          8.833500            NaN
755                           Colombia  2020          2.569500            NaN
776                            Comoros  2020          2.776000            NaN
777                              Congo  2000          2.160000            NaN
778                              Congo  2001          2.330000            NaN
779                              Congo  2002          2.250000            NaN
780                              Congo  2003          2.630000            NaN
781                              Congo  2004          2.710000            NaN
782                              Congo  2005          2.710000            NaN
783                              Congo  2006          3.270000            NaN
784                              Congo  2007          3.110000            NaN
785                              Congo  2008          3.130000            NaN
786                              Congo  2009          3.210000            NaN
787                              Congo  2010          3.180000            NaN
788                              Congo  2011          4.140000            NaN
789                              Congo  2012          4.310000            NaN
790                              Congo  2013          4.570000            NaN
791                              Congo  2014          4.240000            NaN
792                              Congo  2015          4.620000            NaN
793                              Congo  2016          5.390000            NaN
794                              Congo  2017          5.640000            NaN
795                              Congo  2018          6.120000            NaN
796                              Congo  2019          6.550000            NaN
797                              Congo  2020          3.813500            NaN
818                         Costa Rica  2020          2.405500            NaN
839                            Croatia  2020          3.716500            NaN
860                               Cuba  2020          2.035000            NaN
881                             Cyprus  2020          3.248000            NaN
902                            Czechia  2020          5.443000            NaN
923                            Denmark  2020          2.655000            NaN
944                           Djibouti  2020          4.167500            NaN
965                           Dominica  2020          2.917000            NaN
986                 Dominican Republic  2020          2.785500            NaN
1007                           Ecuador  2020          3.358500            NaN
1008                             Egypt  2000          3.270000            NaN
1009                             Egypt  2001          3.590000            NaN
1010                             Egypt  2002          3.590000            NaN
1011                             Egypt  2003          3.620000            NaN
1012                             Egypt  2004          3.790000            NaN
1013                             Egypt  2005          4.170000            NaN
1014                             Egypt  2006          4.120000            NaN
1015                             Egypt  2007          4.110000            NaN
1016                             Egypt  2008          3.970000            NaN
1017                             Egypt  2009          3.880000            NaN
1018                             Egypt  2010          3.660000            NaN
1019                             Egypt  2011          3.770000            NaN
1020                             Egypt  2012          3.800000            NaN
1021                             Egypt  2013          3.620000            NaN
1022                             Egypt  2014          3.630000            NaN
1023                             Egypt  2015          3.460000            NaN
1024                             Egypt  2016          3.640000            NaN
1025                             Egypt  2017          3.670000            NaN
1026                             Egypt  2018          3.590000            NaN
1027                             Egypt  2019          3.410000            NaN
1028                             Egypt  2020          3.718000            NaN
1049                       El Salvador  2020          3.653000            NaN
1070                 Equatorial Guinea  2020          2.575000            NaN
1112                           Estonia  2020          6.232000            NaN
1133                          Eswatini  2020          5.327500            NaN
1154                          Ethiopia  2020         14.084500            NaN
1175                              Fiji  2020          2.438000            NaN
1196                           Finland  2020          6.004000            NaN
1217                            France  2020          3.955000            NaN
1239                             Gabon  2020          6.322500            NaN
1240                            Gambia  2000          3.130000            NaN
1241                            Gambia  2001          3.100000            NaN
1242                            Gambia  2002          3.230000            NaN
1243                            Gambia  2003          3.050000            NaN
1244                            Gambia  2004          2.940000            NaN
1245                            Gambia  2005          3.050000            NaN
1246                            Gambia  2006          3.200000            NaN
1247                            Gambia  2007          3.220000            NaN
1248                            Gambia  2008          3.090000            NaN
1249                            Gambia  2009          3.090000            NaN
1250                            Gambia  2010          2.920000            NaN
1251                            Gambia  2011          3.240000            NaN
1252                            Gambia  2012          3.130000            NaN
1253                            Gambia  2013          3.010000            NaN
1254                            Gambia  2014          3.340000            NaN
1255                            Gambia  2015          3.480000            NaN
1256                            Gambia  2016          3.450000            NaN
1257                            Gambia  2017          3.290000            NaN
1258                            Gambia  2018          3.080000            NaN
1259                            Gambia  2019          2.970000            NaN
1260                            Gambia  2020          3.150500            NaN
1281                           Georgia  2020          4.177000            NaN
1302                           Germany  2020          3.496000            NaN
1323                             Ghana  2020          3.516500            NaN
1344                            Greece  2020          3.236500            NaN
1365                           Grenada  2020          2.565000            NaN
1386                         Guatemala  2020          4.195500            NaN
1407                            Guinea  2020          7.348000            NaN
1428                     Guinea-Bissau  2020         10.442000            NaN
1449                            Guyana  2020          4.821500            NaN
1470                             Haiti  2020          5.691500            NaN
1491                          Honduras  2020          4.853000            NaN
1512                           Hungary  2020          4.362000            NaN
1533                           Iceland  2020         12.510000            NaN
1554                             India  2020          5.306500            NaN
1575                         Indonesia  2020          4.203500            NaN
1596                              Iraq  2020          5.310500            NaN
1617                           Ireland  2020          2.275000            NaN
1638                            Israel  2020          3.411000            NaN
1659                             Italy  2020          2.782000            NaN
1680                           Jamaica  2020          4.742000            NaN
1701                             Japan  2020          4.128500            NaN
1722                            Jordan  2020          4.022000            NaN
1743                        Kazakhstan  2020          8.026000            NaN
1764                             Kenya  2020          5.874000            NaN
1785                          Kiribati  2020          6.135000            NaN
1806                            Kuwait  2020          6.671500            NaN
1848                            Latvia  2020          3.988500            NaN
1869                           Lebanon  2020          3.195000            NaN
1890                           Lesotho  2020         10.804500            NaN
1911                           Liberia  2020         13.280000            NaN
1932                             Libya  2020          7.669500            NaN
1953                         Lithuania  2020          4.566000            NaN
1974                        Luxembourg  2020          3.075500            NaN
1995                        Madagascar  2020          6.531000            NaN
2016                            Malawi  2020          4.259000            NaN
2037                          Malaysia  2020          5.226000            NaN
2058                          Maldives  2020          2.213500            NaN
2079                              Mali  2020          4.928500            NaN
2100                             Malta  2020          2.398500            NaN
2121                        Mauritania  2020          2.722000            NaN
2142                         Mauritius  2020          2.629000            NaN
2163                            Mexico  2020          3.612500            NaN
2184                          Mongolia  2020          7.688000            NaN
2198                        Montenegro  2020          3.961538            NaN
2219                           Morocco  2020          3.466000            NaN
2240                        Mozambique  2020         16.922000            NaN
2261                           Myanmar  2020          5.316500            NaN
2282                           Namibia  2020          3.543500            NaN
2303                             Nauru  2020         10.141000            NaN
2324                             Nepal  2020          6.067500            NaN
2345                       Netherlands  2020          3.762500            NaN
2387                       New Zealand  2020          4.620500            NaN
2408                         Nicaragua  2020          4.773000            NaN
2429                             Niger  2020          5.411500            NaN
2450                           Nigeria  2020          7.319000            NaN
2471                   North Macedonia  2020          4.487500            NaN
2492                            Norway  2020          4.049500            NaN
2513                              Oman  2020          6.835500            NaN
2534                          Pakistan  2020          5.105500            NaN
2555                            Panama  2020          1.841500            NaN
2576                  Papua New Guinea  2020          6.061500            NaN
2597                          Paraguay  2020          3.278000            NaN
2618                              Peru  2020          2.734500            NaN
2639                       Philippines  2020          3.376000            NaN
2660                            Poland  2020          4.672500            NaN
2681                          Portugal  2020          3.013500            NaN
2682                       Puerto Rico  2000          0.110000            NaN
2683                       Puerto Rico  2001          0.180000            NaN
2684                       Puerto Rico  2002          0.180000            NaN
2685                       Puerto Rico  2003          0.210000            NaN
2686                       Puerto Rico  2004          0.180000            NaN
2687                       Puerto Rico  2005          0.180000            NaN
2688                       Puerto Rico  2006          0.200000            NaN
2689                       Puerto Rico  2007          0.210000            NaN
2690                       Puerto Rico  2008          0.230000            NaN
2691                       Puerto Rico  2009          0.220000            NaN
2692                       Puerto Rico  2010          0.230000            NaN
2693                       Puerto Rico  2011          0.220000            NaN
2694                       Puerto Rico  2012          0.390000            NaN
2695                       Puerto Rico  2013          0.470000            NaN
2696                       Puerto Rico  2014          0.490000            NaN
2697                       Puerto Rico  2015          0.470000            NaN
2698                       Puerto Rico  2016          0.530000            NaN
2699                       Puerto Rico  2017          0.420000            NaN
2700                       Puerto Rico  2018          0.550000            NaN
2701                       Puerto Rico  2019          0.630000            NaN
2702                       Puerto Rico  2020          0.315000            NaN
2723                             Qatar  2020          7.638500            NaN
2744                           Romania  2020          3.783000            NaN
2765                            Rwanda  2020          5.594500            NaN
2766             Saint Kitts and Nevis  2000          3.090000            NaN
2767             Saint Kitts and Nevis  2001          3.020000            NaN
2768             Saint Kitts and Nevis  2002          3.230000            NaN
2769             Saint Kitts and Nevis  2003          3.440000            NaN
2770             Saint Kitts and Nevis  2004          3.490000            NaN
2771             Saint Kitts and Nevis  2005          2.980000            NaN
2772             Saint Kitts and Nevis  2006          2.540000            NaN
2773             Saint Kitts and Nevis  2007          2.670000            NaN
2774             Saint Kitts and Nevis  2008          2.510000            NaN
2775             Saint Kitts and Nevis  2009          2.680000            NaN
2776             Saint Kitts and Nevis  2010          2.730000            NaN
2777             Saint Kitts and Nevis  2011          2.770000            NaN
2778             Saint Kitts and Nevis  2012          2.780000            NaN
2779             Saint Kitts and Nevis  2013          2.640000            NaN
2780             Saint Kitts and Nevis  2014          2.530000            NaN
2781             Saint Kitts and Nevis  2015          2.560000            NaN
2782             Saint Kitts and Nevis  2016          2.560000            NaN

## **1.7 Mixed Approach for CO2 Emissions Imputation Process**
**Features:**  
- `CO2_Emissions`

1️⃣ Adding Missing CO2 Emissions Data
- Merged external CO2 per capita data from World Bank Data for countries:
Bahamas, Congo, Egypt, Gambia, St. Kitts and Nevis, St. Lucia, St. Vincent and Grenadines, Yemen, Puerto Rico, and Turkey.

2️⃣ Forward-filling the rest of missing CO2 Emissions Data since missing values are scattered acorss years or 2020.

In [492]:
CO2_data = pd.read_csv('CO2_cleaned.csv')
CO2_data.head()

    Entity  Year  CO2_Emissions
0  Bahamas  2000       3.078111
1  Bahamas  2001       3.025903
2  Bahamas  2002       3.275797
3  Bahamas  2003       2.410777
4  Bahamas  2004       2.571060

In [496]:

for index, row in CO2_data.iterrows():
    df.loc[(df['Entity'] == row['Entity']) & (df['Year'] == row['Year']), 'CO2_Emissions'] = row['CO2_Emissions']

print(df[df['Entity'] == 'Bahamas'])

      Entity  Year  Electricity_Access  Clean_Cooking_Fuels  \
231  Bahamas  2000               100.0                100.0
232  Bahamas  2001               100.0                100.0
233  Bahamas  2002               100.0                100.0
234  Bahamas  2003               100.0                100.0
235  Bahamas  2004               100.0                100.0
236  Bahamas  2005               100.0                100.0
237  Bahamas  2006               100.0                100.0
238  Bahamas  2007               100.0                100.0
239  Bahamas  2008               100.0                100.0
240  Bahamas  2009               100.0                100.0
241  Bahamas  2010               100.0                100.0
242  Bahamas  2011               100.0                100.0
243  Bahamas  2012               100.0                100.0
244  Bahamas  2013               100.0                100.0
245  Bahamas  2014               100.0                100.0
246  Bahamas  2015               100.0                100.0
247  Bahamas  2016               100.0                100.0
248  Bahamas  2017               100.0                100.0
249  Bahamas  2018               100.0                100.0
250  Bahamas  2019               100.0                100.0
251  Bahamas  2020               100.0                100.0

     Renewable_Capacity  Financial_Flows  Renewable_Share  Fossil_Electricity  \
231                0.00              0.0             0.00                1.57
232                0.00              0.0             0.42                1.63
233                0.00              0.0             0.38                1.72
234                0.00              0.0             1.54                1.81
235                0.00              0.0             1.59                1.79
236                0.00              0.0             1.71                1.89
237                0.00              0.0             2.01                1.93
238                0.30              0.0             3.54                2.05
239                0.29              0.0             1.97                2.05
240                0.57              0.0             1.83                1.95
241                0.85              0.0             1.65                1.89
242                1.14              0.0             1.42                1.93
243                1.71              0.0             1.18                1.79
244                1.70              0.0             0.96                1.77
245                3.44              0.0             1.14                1.81
246                3.47              0.0             1.54                1.88
247                3.84              0.0             1.53                1.85
248                3.66          20000.0             1.44                1.87
249                3.54         110000.0             1.02                2.14
250                5.88         560000.0             1.14                2.10
251                5.68              0.0            23.30                1.99

     Nuclear_Electricity  Renewable_Electricity  Low_Carbon_Electricity  \
231                  0.0                    0.0                     0.0
232                  0.0                    0.0                     0.0
233                  0.0                    0.0                     0.0
234                  0.0                    0.0                     0.0
235                  0.0                    0.0                     0.0
236                  0.0                    0.0                     0.0
237                  0.0                    0.0                     0.0
238                  0.0                    0.0                     0.0
239                  0.0                    0.0                     0.0
240                  0.0                    0.0                     0.0
241                  0.0                    0.0                     0.0
242                  0.0                    0.0                     0.0
243                  0.0                    0.0                     0.0
244                  0.0                    0.0                     0.0
245                  0.0                    0.0                     0.0
246                  0.0                    0.0                     0.0
247                  0.0                    0.0                     0.0
248                  0.0                    0.0                     0.0
249                  0.0                    0.0                     0.0
250                  0.0                    0.0                     0.0
251                  0.0                    0.0                     0.0

     Energy_Consumption  Energy_Intensity  CO2_Emissions  \
231           50650.190            2.3300       3.078111
232           50899.527            2.1900       3.025903
233           52098.810            2.2300       3.275797
234           35908.117            2.3200       2.410777
235           39267.470            2.2700       2.571060
236           37244.637            2.1000       2.501061
237           42663.530            2.0000            NaN
238           48444.410            2.0000            NaN
239           46670.273            2.0800       3.801240
240           34584.957            2.2300       3.120917
241           35531.060            2.1400       3.491093
242           30982.486            2.3500       2.297642
243           35422.555            2.5000       2.708346
244           32656.572            2.9800       2.878985
245           31772.066            2.6500       2.972027
246           30096.480            2.3300       2.906998
247           31247.096            2.1200       3.209081
248           36977.280            2.1800       3.517677
249           39876.790            2.7200       3.928019
250           39636.066            2.5300       4.489517
251           33301.770            2.3125       3.631054

     Renewables_Percentage  GDP_Growth  GDP_Per_Capita  Population_Density  \
231                    0.0    4.148419     24940.07751                41.0
232                    0.0    2.626010     25371.92377                41.0
233                    0.0    2.704956     26781.61959                41.0
234                    0.0   -1.264917     26429.12478                41.0
235                    0.0    0.882374     26650.29342                41.0
236                    0.0    3.396084     28602.41819                41.0
237                    0.0    2.516592     29184.78651                41.0
238                    0.0    1.446100     30051.84896                41.0
239                    0.0   -2.323648     29392.38244                41.0
240                    0.0   -4.175428     27512.91310                41.0
241                    0.0    1.538662     27473.10043                41.0
242                    0.0    0.613171     27090.83768                41.0
243                    0.0    2.997903     28552.02427                41.0
244                    0.0   -2.863309     27432.95343                41.0
245                    0.0    1.847261     28705.61708                41.0
246                    0.0    0.996759     30289.40225                41.0
247                    0.0   -0.961909     30266.58592                41.0
248                    0.0    2.799519     31337.18325                41.0
249                    0.0    2.629890     32124.40511                41.0
250                    0.0   -1.357265     32979.54013                41.0
251                    0.0  -21.423463     25155.67254                41.0

     Land_Area   Latitude  Longitude
231    13878.0  25.025885 -78.035889
232    13878.0  25.025885 -78.035889
233    13878.0  25.025885 -78.035889
234    13878.0  25.025885 -78.035889
235    13878.0  25.025885 -78.035889
236    13878.0  25.025885 -78.035889
237    13878.0  25.025885 -78.035889
238    13878.0  25.025885 -78.035889
239    13878.0  25.025885 -78.035889
240    13878.0  25.025885 -78.035889
241    13878.0  25.025885 -78.035889
242    13878.0  25.025885 -78.035889
243    13878.0  25.025885 -78.035889
244    13878.0  25.025885 -78.035889
245    13878.0  25.025885 -78.035889
246    13878.0  25.025885 -78.035889
247    13878.0  25.025885 -78.035889
248    13878.0  25.025885 -78.035889
249    13878.0  25.025885 -78.035889
250    13878.0  25.025885 -78.035889
251    13878.0  25.025885 -78.035889

In [504]:
missing_CO2 = df[df[['CO2_Emissions']].isna().any(axis=1)]

# Display the relevant columns for analysis
print(missing_CO2[['Entity', 'Year', 'CO2_Emissions']])

                                Entity  Year  CO2_Emissions
20                         Afghanistan  2020            NaN
41                             Albania  2020            NaN
62                             Algeria  2020            NaN
83                              Angola  2020            NaN
104                Antigua and Barbuda  2020            NaN
125                          Argentina  2020            NaN
146                            Armenia  2020            NaN
164                              Aruba  2017            NaN
165                              Aruba  2018            NaN
166                              Aruba  2019            NaN
167                              Aruba  2020            NaN
188                          Australia  2020            NaN
209                            Austria  2020            NaN
230                         Azerbaijan  2020            NaN
237                            Bahamas  2006            NaN
238                            Bahamas  2007            NaN
272                            Bahrain  2020            NaN
293                         Bangladesh  2020            NaN
314                           Barbados  2020            NaN
335                            Belarus  2020            NaN
356                            Belgium  2020            NaN
377                             Belize  2020            NaN
398                              Benin  2020            NaN
416                            Bermuda  2017            NaN
417                            Bermuda  2018            NaN
418                            Bermuda  2019            NaN
419                            Bermuda  2020            NaN
440                             Bhutan  2020            NaN
461             Bosnia and Herzegovina  2020            NaN
482                           Botswana  2020            NaN
503                             Brazil  2020            NaN
524                           Bulgaria  2020            NaN
545                       Burkina Faso  2020            NaN
566                            Burundi  2020            NaN
587                           Cambodia  2020            NaN
608                           Cameroon  2020            NaN
629                             Canada  2020            NaN
647                     Cayman Islands  2017            NaN
648                     Cayman Islands  2018            NaN
649                     Cayman Islands  2019            NaN
650                     Cayman Islands  2020            NaN
671           Central African Republic  2020            NaN
692                               Chad  2020            NaN
713                              Chile  2020            NaN
734                              China  2020            NaN
755                           Colombia  2020            NaN
776                            Comoros  2020            NaN
783                              Congo  2006            NaN
784                              Congo  2007            NaN
818                         Costa Rica  2020            NaN
839                            Croatia  2020            NaN
860                               Cuba  2020            NaN
881                             Cyprus  2020            NaN
902                            Czechia  2020            NaN
923                            Denmark  2020            NaN
944                           Djibouti  2020            NaN
965                           Dominica  2020            NaN
986                 Dominican Republic  2020            NaN
1007                           Ecuador  2020            NaN
1014                             Egypt  2006            NaN
1015                             Egypt  2007            NaN
1049                       El Salvador  2020            NaN
1070                 Equatorial Guinea  2020            NaN
1112                           Estonia  2020            NaN
1133                          Eswatini  2020            NaN
1154                          Ethiopia  2020            NaN
1175                              Fiji  2020            NaN
1196                           Finland  2020            NaN
1217                            France  2020            NaN
1239                             Gabon  2020            NaN
1246                            Gambia  2006            NaN
1247                            Gambia  2007            NaN
1281                           Georgia  2020            NaN
1302                           Germany  2020            NaN
1323                             Ghana  2020            NaN
1344                            Greece  2020            NaN
1365                           Grenada  2020            NaN
1386                         Guatemala  2020            NaN
1407                            Guinea  2020            NaN
1428                     Guinea-Bissau  2020            NaN
1449                            Guyana  2020            NaN
1470                             Haiti  2020            NaN
1491                          Honduras  2020            NaN
1512                           Hungary  2020            NaN
1533                           Iceland  2020            NaN
1554                             India  2020            NaN
1575                         Indonesia  2020            NaN
1596                              Iraq  2020            NaN
1617                           Ireland  2020            NaN
1638                            Israel  2020            NaN
1659                             Italy  2020            NaN
1680                           Jamaica  2020            NaN
1701                             Japan  2020            NaN
1722                            Jordan  2020            NaN
1743                        Kazakhstan  2020            NaN
1764                             Kenya  2020            NaN
1785                          Kiribati  2020            NaN
1806                            Kuwait  2020            NaN
1848                            Latvia  2020            NaN
1869                           Lebanon  2020            NaN
1890                           Lesotho  2020            NaN
1911                           Liberia  2020            NaN
1932                             Libya  2020            NaN
1953                         Lithuania  2020            NaN
1974                        Luxembourg  2020            NaN
1995                        Madagascar  2020            NaN
2016                            Malawi  2020            NaN
2037                          Malaysia  2020            NaN
2058                          Maldives  2020            NaN
2079                              Mali  2020            NaN
2100                             Malta  2020            NaN
2121                        Mauritania  2020            NaN
2142                         Mauritius  2020            NaN
2163                            Mexico  2020            NaN
2184                          Mongolia  2020            NaN
2198                        Montenegro  2020            NaN
2219                           Morocco  2020            NaN
2240                        Mozambique  2020            NaN
2261                           Myanmar  2020            NaN
2282                           Namibia  2020            NaN
2303                             Nauru  2020            NaN
2324                             Nepal  2020            NaN
2345                       Netherlands  2020            NaN
2387                       New Zealand  2020            NaN
2408                         Nicaragua  2020            NaN
2429                             Niger  2020            NaN
2450                           Nigeria  2020            NaN
2471                   North Macedonia  2020            NaN
2492                            Norway  2020            NaN
2513                              Oman  2020            NaN
2534                          Pakistan  2020            NaN
2555                            Panama  2020            NaN
2576                  Papua New Guinea  2020            NaN
2597                          Paraguay  2020            NaN
2618                              Peru  2020            NaN
2639                       Philippines  2020            NaN
2660                            Poland  2020            NaN
2681                          Portugal  2020            NaN
2688                       Puerto Rico  2006            NaN
2689                       Puerto Rico  2007            NaN
2723                             Qatar  2020            NaN
2744                           Romania  2020            NaN
2765                            Rwanda  2020            NaN
2772             Saint Kitts and Nevis  2006            NaN
2773             Saint Kitts and Nevis  2007            NaN
2793                       Saint Lucia  2006            NaN
2794                       Saint Lucia  2007            NaN
2814  Saint Vincent and the Grenadines  2006            NaN
2815  Saint Vincent and the Grenadines  2007            NaN
2849                             Samoa  2020            NaN
2870             Sao Tome and Principe  2020            NaN
2891                      Saudi Arabia  2020            NaN
2912                           Senegal  2020            NaN
2926                            Serbia  2020            NaN
2947                        Seychelles  2020            NaN
2968                      Sierra Leone  2020            NaN
2989                         Singapore  2020            NaN
3031                          Slovenia  2020            NaN
3052                   Solomon Islands  2020            NaN
3073                           Somalia  2020            NaN
3094                      South Africa  2020            NaN
3102                       South Sudan  2020            NaN
3123                             Spain  2020            NaN
3144                         Sri Lanka  2020            NaN
3165                             Sudan  2020            NaN
3186                          Suriname  2020            NaN
3207                            Sweden  2020            NaN
3228                       Switzerland  2020            NaN
3249                        Tajikistan  2020            NaN
3270                          Thailand  2020            NaN
3291                              Togo  2020            NaN
3312                             Tonga  2020            NaN
3333               Trinidad and Tobago  2020            NaN
3354                           Tunisia  2020            NaN
3361                            Turkey  2006            NaN
3362                            Turkey  2007            NaN
3396                      Turkmenistan  2020            NaN
3417                            Tuvalu  2020            NaN
3438                            Uganda  2020            NaN
3459                           Ukraine  2020            NaN
3480              United Arab Emirates  2020            NaN
3501                    United Kingdom  2020            NaN
3522                     United States  2020            NaN
3543                           Uruguay  2020            NaN
3564                        Uzbekistan  2020            NaN
3585                           Vanuatu  2020            NaN
3592                             Yemen  2006            NaN
3593                             Yemen  2007            NaN
3627                            Zambia  2020            NaN
3648                          Zimbabwe  2020            NaN

In [506]:
df['CO2_Emissions'] = df['CO2_Emissions'].ffill()

In [508]:
print(df.isnull().sum())

Entity                    0
Year                      0
Electricity_Access        0
Clean_Cooking_Fuels       0
Renewable_Capacity        0
Financial_Flows           0
Renewable_Share           0
Fossil_Electricity        0
Nuclear_Electricity       0
Renewable_Electricity     0
Low_Carbon_Electricity    0
Energy_Consumption        0
Energy_Intensity          0
CO2_Emissions             0
Renewables_Percentage     0
GDP_Growth                0
GDP_Per_Capita            0
Population_Density        0
Land_Area                 0
Latitude                  0
Longitude                 0
dtype: int64

## 2. Data Cleaning & Transformation 
- Convert categorical variables (e.g., "Entity" and "Density") into numerical formats.  
- Standardize units across energy and economic indicators.  
- Normalize numerical features to ensure comparability.

In [512]:
df.dtypes

Entity                     object
Year                        int64
Electricity_Access        float64
Clean_Cooking_Fuels       float64
Renewable_Capacity        float64
Financial_Flows           float64
Renewable_Share           float64
Fossil_Electricity        float64
Nuclear_Electricity       float64
Renewable_Electricity     float64
Low_Carbon_Electricity    float64
Energy_Consumption        float64
Energy_Intensity          float64
CO2_Emissions             float64
Renewables_Percentage     float64
GDP_Growth                float64
GDP_Per_Capita            float64
Population_Density        float64
Land_Area                 float64
Latitude                  float64
Longitude                 float64
dtype: object

### 2.1 Converting data into correct types

In [482]:
df["Population_Density"] = df["Population_Density"].str.replace(",", "").astype(float)

In [484]:
print(df[["Entity", "Year", "Population_Density"]].dtypes)  # Should show float for Population_Density
print(df["Population_Density"].isnull().sum())  # Should return 0

Entity                 object
Year                    int64
Population_Density    float64
dtype: object
0

In [486]:
df["Population_Density"] = pd.to_numeric(df["Population_Density"], errors="coerce")

In [488]:
print(df["Population_Density"].dtype)
print(df["Population_Density"].isnull().sum())

float64
0

In [490]:
country_mapping = dict(enumerate(df["Entity"].astype("category").cat.categories))
print(country_mapping)

{0: 'Afghanistan', 1: 'Albania', 2: 'Algeria', 3: 'Angola', 4: 'Antigua and Barbuda', 5: 'Argentina', 6: 'Armenia', 7: 'Aruba', 8: 'Australia', 9: 'Austria', 10: 'Azerbaijan', 11: 'Bahamas', 12: 'Bahrain', 13: 'Bangladesh', 14: 'Barbados', 15: 'Belarus', 16: 'Belgium', 17: 'Belize', 18: 'Benin', 19: 'Bermuda', 20: 'Bhutan', 21: 'Bosnia and Herzegovina', 22: 'Botswana', 23: 'Brazil', 24: 'Bulgaria', 25: 'Burkina Faso', 26: 'Burundi', 27: 'Cambodia', 28: 'Cameroon', 29: 'Canada', 30: 'Cayman Islands', 31: 'Central African Republic', 32: 'Chad', 33: 'Chile', 34: 'China', 35: 'Colombia', 36: 'Comoros', 37: 'Congo', 38: 'Costa Rica', 39: 'Croatia', 40: 'Cuba', 41: 'Cyprus', 42: 'Czechia', 43: 'Denmark', 44: 'Djibouti', 45: 'Dominica', 46: 'Dominican Republic', 47: 'Ecuador', 48: 'Egypt', 49: 'El Salvador', 50: 'Equatorial Guinea', 51: 'Estonia', 52: 'Eswatini', 53: 'Ethiopia', 54: 'Fiji', 55: 'Finland', 56: 'France', 57: 'Gabon', 58: 'Gambia', 59: 'Georgia', 60: 'Germany', 61: 'Ghana', 62: 'Greece', 63: 'Grenada', 64: 'Guatemala', 65: 'Guinea', 66: 'Guinea-Bissau', 67: 'Guyana', 68: 'Haiti', 69: 'Honduras', 70: 'Hungary', 71: 'Iceland', 72: 'India', 73: 'Indonesia', 74: 'Iraq', 75: 'Ireland', 76: 'Israel', 77: 'Italy', 78: 'Jamaica', 79: 'Japan', 80: 'Jordan', 81: 'Kazakhstan', 82: 'Kenya', 83: 'Kiribati', 84: 'Kuwait', 85: 'Latvia', 86: 'Lebanon', 87: 'Lesotho', 88: 'Liberia', 89: 'Libya', 90: 'Lithuania', 91: 'Luxembourg', 92: 'Madagascar', 93: 'Malawi', 94: 'Malaysia', 95: 'Maldives', 96: 'Mali', 97: 'Malta', 98: 'Mauritania', 99: 'Mauritius', 100: 'Mexico', 101: 'Mongolia', 102: 'Montenegro', 103: 'Morocco', 104: 'Mozambique', 105: 'Myanmar', 106: 'Namibia', 107: 'Nauru', 108: 'Nepal', 109: 'Netherlands', 110: 'New Zealand', 111: 'Nicaragua', 112: 'Niger', 113: 'Nigeria', 114: 'North Macedonia', 115: 'Norway', 116: 'Oman', 117: 'Pakistan', 118: 'Panama', 119: 'Papua New Guinea', 120: 'Paraguay', 121: 'Peru', 122: 'Philippines', 123: 'Poland', 124: 'Portugal', 125: 'Puerto Rico', 126: 'Qatar', 127: 'Romania', 128: 'Rwanda', 129: 'Saint Kitts and Nevis', 130: 'Saint Lucia', 131: 'Saint Vincent and the Grenadines', 132: 'Samoa', 133: 'Sao Tome and Principe', 134: 'Saudi Arabia', 135: 'Senegal', 136: 'Serbia', 137: 'Seychelles', 138: 'Sierra Leone', 139: 'Singapore', 140: 'Slovenia', 141: 'Solomon Islands', 142: 'Somalia', 143: 'South Africa', 144: 'South Sudan', 145: 'Spain', 146: 'Sri Lanka', 147: 'Sudan', 148: 'Suriname', 149: 'Sweden', 150: 'Switzerland', 151: 'Tajikistan', 152: 'Thailand', 153: 'Togo', 154: 'Tonga', 155: 'Trinidad and Tobago', 156: 'Tunisia', 157: 'Turkey', 158: 'Turkmenistan', 159: 'Tuvalu', 160: 'Uganda', 161: 'Ukraine', 162: 'United Arab Emirates', 163: 'United Kingdom', 164: 'United States', 165: 'Uruguay', 166: 'Uzbekistan', 167: 'Vanuatu', 168: 'Yemen', 169: 'Zambia', 170: 'Zimbabwe'}

In [25]:
#["Entity"] = df["Entity"].astype("category").cat.codes  # Convert country names to numeric codes
#df["Entity"].dtypes

### 2.2 Normalize and Standardize Data

In [530]:
from sklearn.preprocessing import MinMaxScaler
scaler = MinMaxScaler()
df[['Energy_Consumption', 'CO2_Emissions']] = scaler.fit_transform(df[['Energy_Consumption', 'CO2_Emissions']])

#Energy intensity (MJ/$2011 PPP GPT): since this value measures efficieny per unit of economic output, normalization may be better than simple conversion

## 3. Handling Outilers

In [522]:
# Remove extreme outliers (e.g., beyond 3 standard deviations)
for col in ["GDP_Per_Capita", "CO2_Emissions", "Renewable_Share", "Energy_Intensity"]:
    df = df[np.abs(df[col] - df[col].mean()) <= (3 * df[col].std())]

## 4. Feature Engineering

In [534]:
#New insights to explore
df["Energy_Dependency"] = df["Renewable_Share"] * df["Financial_Flows"]
df["CO2_Intensity_Per_Capita"] = df["CO2_Emissions"] / df["Population_Density"]

df['Renewables_to_Fossil'] = df['Renewable_Electricity'] / (df['Fossil_Electricity'] + 1e-6)
df['Energy_Efficiency'] = df['GDP_Per_Capita'] / df['Energy_Consumption']

In [536]:
#Generate interaction terms for neural models
df['Renewable_Nuclear_Interaction'] = df['Renewable_Electricity'] * df['Nuclear_Electricity']

### 5. Geospatial Data Preparation

In [539]:
df['Latitude'] = df['Latitude'].astype(float)
df['Longitude'] = df['Longitude'].astype(float)

In [543]:
import os
os.environ["LOKY_MAX_CPU_COUNT"] = "4"  # Replace "4" with the number of logical cores detected

In [545]:
from sklearn.cluster import KMeans
geo_features = df[['Latitude', 'Longitude', 'Energy_Consumption', 'Renewable_Share']]
kmeans = KMeans(n_clusters=5, random_state=42)
df['Energy_Cluster'] = kmeans.fit_predict(geo_features)

In [551]:
df.groupby('Energy_Cluster')[['Energy_Consumption', 'Renewable_Share']].mean()

                Energy_Consumption  Renewable_Share
Energy_Cluster
0                         0.068466         0.267256
1                         0.095371         0.521315
2                         0.074777         0.355978
3                         0.078367         0.297996
4                         0.103854         0.285222

### 6. Check Data Integrity

In [557]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 3363 entries, 0 to 3648
Data columns (total 27 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   Entity                         3363 non-null   object
 1   Year                           3363 non-null   int64
 2   Electricity_Access             3363 non-null   float64
 3   Clean_Cooking_Fuels            3363 non-null   float64
 4   Renewable_Capacity             3363 non-null   float64
 5   Financial_Flows                3363 non-null   float64
 6   Renewable_Share                3363 non-null   float64
 7   Fossil_Electricity             3363 non-null   float64
 8   Nuclear_Electricity            3363 non-null   float64
 9   Renewable_Electricity          3363 non-null   float64
 10  Low_Carbon_Electricity         3363 non-null   float64
 11  Energy_Consumption             3363 non-null   float64
 12  Energy_Intensity               3363 non-null   float64
 13  CO2_Emissions                  3363 non-null   float64
 14  Renewables_Percentage          3363 non-null   float64
 15  GDP_Growth                     3363 non-null   float64
 16  GDP_Per_Capita                 3363 non-null   float64
 17  Population_Density             3363 non-null   float64
 18  Land_Area                      3363 non-null   float64
 19  Latitude                       3363 non-null   float64
 20  Longitude                      3363 non-null   float64
 21  Energy_Dependency              3363 non-null   float64
 22  CO2_Intensity_Per_Capita       3363 non-null   float64
 23  Renewables_to_Fossil           3363 non-null   float64
 24  Energy_Efficiency              3363 non-null   float64
 25  Renewable_Nuclear_Interaction  3363 non-null   float64
 26  Energy_Cluster                 3363 non-null   int32
dtypes: float64(24), int32(1), int64(1), object(1)
memory usage: 722.5+ KB

In [555]:
df.describe()

,Year,Electricity_Access,Clean_Cooking_Fuels,Renewable_Capacity,Financial_Flows,Renewable_Share,Fossil_Electricity,Nuclear_Electricity,Renewable_Electricity,Low_Carbon_Electricity,Energy_Consumption,Energy_Intensity,CO2_Emissions,Renewables_Percentage,GDP_Growth,GDP_Per_Capita,Population_Density,Land_Area,Latitude,Longitude,Energy_Dependency,CO2_Intensity_Per_Capita,Renewables_to_Fossil,Energy_Efficiency,Renewable_Nuclear_Interaction,Energy_Cluster
count,3363.000000,3363.000000,3363.000000,3363.000000,3.363000e+03,3363.000000,3363.000000,3363.000000,3363.000000,3363.000000,3363.000000,3363.000000,3363.000000,3363.000000,3363.000000,3363.000000,3363.000000,3.363000e+03,3363.000000,3363.000000,3.363000e+03,3363.000000,3.363000e+03,3363.000000,3363.000000,3363.000000
mean,2010.052632,78.038951,63.010690,82.089813,4.212583e+07,0.344130,38.620358,8.184448,16.259396,36.726140,0.089107,0.308141,0.032138,4.779823,3.388259,0.087316,226.573595,5.536645e+05,17.395436,13.318431,1.868008e+07,0.001176,3.378482e+05,inf,792.199051,2.119536
std,6.054769,30.487737,38.669897,217.522500,2.069441e+08,0.302431,104.505290,40.383930,50.974353,33.805402,0.123808,0.171159,0.082526,10.761680,5.829014,0.119501,706.775133,1.292113e+06,24.143428,65.794382,1.321540e+08,0.006084,3.545374e+06,NaN,4423.164734,1.632867
min,2000.000000,1.252269,0.000000,0.000000,0.000000e+00,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,-62.075920,0.000013,2.000000,2.100000e+01,-40.900557,-175.198242,0.000000e+00,0.000000,0.000000e+00,0.006015,0.000000,0.000000
25%,2005.000000,56.564420,23.600000,0.000000,0.000000e+00,0.082726,0.280000,0.000000,0.055000,3.451780,0.011121,0.191945,0.000558,0.000000,1.373551,0.009401,31.000000,2.775000e+04,1.650801,-14.452362,0.000000e+00,0.000006,3.024881e-02,0.592981,0.000000,1.000000
50%,2010.000000,97.500000,83.150000,9.240000,0.000000e+00,0.242607,3.020000,0.000000,1.490000,28.828829,0.044440,0.257395,0.003399,0.000000,3.577015,0.034000,87.000000,1.184840e+05,15.783471,18.732207,0.000000e+00,0.000060,2.748091e-01,0.977274,0.000000,2.000000
75%,2015.000000,100.000000,100.000000,67.210000,2.880000e+06,0.555966,28.845000,0.000000,9.420000,63.441536,0.114584,0.362618,0.022931,4.046508,5.811262,0.109750,214.000000,5.279680e+05,38.861034,45.038189,6.585126e+05,0.000307,1.526643e+00,1.462847,0.000000,4.000000
max,2020.000000,100.000000,100.000000,3060.190000,5.202310e+09,1.000000,1276.320000,451.530000,520.010000,100.000010,1.000000,1.000000,1.000000,86.836586,123.139555,0.570076,8358.000000,9.984670e+06,64.963051,178.065032,4.459123e+09,0.059053,6.330000e+07,inf,46918.242800,4.000000

In [559]:
datapath = 'C:/Users/aamal/Desktop/Springboard/Springboard_DataScience/Capstone-3-Energy/data'
energy_data_cleaned = 'energy_data_cleaned.csv'
filepath= os.path.join(datapath, energy_data_cleaned)

df.to_csv(filepath, index= False)
print(f"Data saved successfully to '{filepath}'")

Data saved successfully to 'C:/Users/aamal/Desktop/Springboard/Springboard_DataScience/Capstone-3-Energy/data\energy_data_cleaned.csv'